hunter_add_package(bcos-framework)
hunter_add_package(jsoncpp)
find_package(jsoncpp CONFIG REQUIRED)
find_package(Boost CONFIG REQUIRED log chrono system filesystem iostreams thread program_options)
find_package(Protobuf CONFIG REQUIRED)
find_package(TBB)
find_package(bcos-framework CONFIG REQUIRED)
get_target_property(BCOS_FRAMEWORK_INCLUDE bcos-framework::utilities INTERFACE_INCLUDE_DIRECTORIES)
include_directories(${BCOS_FRAMEWORK_INCLUDE}/bcos-framework)
