hunter_add_package(Boost COMPONENTS all)
hunter_add_package(bcos-utilities)
find_package(Boost CONFIG REQUIRED log chrono system filesystem iostreams thread program_options)
find_package(bcos-utilities CONFIG REQUIRED)
get_target_property(BCOS_UTILITIES_INCLUDE bcos-utilities::bcos-utilities INTERFACE_INCLUDE_DIRECTORIES)
include_directories(${BCOS_UTILITIES_INCLUDE}/bcos-utilities)