hunter_add_package(bcos-storage)
set(CMAKE_FIND_LIBRARY_SUFFIXES .a ${CMAKE_FIND_LIBRARY_SUFFIXES})
find_package(bcos-framework CONFIG REQUIRED)
find_package(zstd CONFIG REQUIRED)
find_package(RocksDB CONFIG REQUIRED)
find_package(Boost CONFIG REQUIRED serialization)
find_package(bcos-storage CONFIG REQUIRED)
get_target_property(BCOS_STORAGE_INCLUDE bcos-storage::bcos-storage INTERFACE_INCLUDE_DIRECTORIES)
include_directories(${BCOS_STORAGE_INCLUDE}/bcos-storage)
