/**
 *  Copyright (C) 2026 FISCO BCOS.
 *  SPDX-License-Identifier: Apache-2.0
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 * @file EthBlockBodyTest.cpp
 * @brief Golden-vector + round-trip tests for EthBlockBody
 * @date 2026/8/18
 */

#include "bcos-rlp-protocol/EthBlockBody.h"
#include "bcos-rlp-protocol/EthBlockHeader.h"
#include "bcos-rlp-protocol/EthWithdrawal.h"
#include <bcos-utilities/DataConvertUtility.h>
#include <boost/test/unit_test.hpp>

using namespace bcos;
using namespace bcos::protocol;

namespace bcos::test
{
BOOST_AUTO_TEST_SUITE(EthBlockBodyTest)

// Golden vectors generated by an independent Python RLP reference.
static const std::string kLondonHeaderHex = "f901fca05555555555555555555555555555555555555555555555555555555555555555a0eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee94ababababababababababababababababababababa01111111111111111111111111111111111111111111111111111111111111111a02222222222222222222222222222222222222222222222222222222222222222a03333333333333333333333333333333333333333333333333333333333333333b90100cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd804d8401c9c380825208846553f10080a04444444444444444444444444444444444444444444444444444444444444444880000000000000000843b9aca00";
static const std::string kShanghaiHeaderHex = "f9021da05555555555555555555555555555555555555555555555555555555555555555a0eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee94ababababababababababababababababababababa01111111111111111111111111111111111111111111111111111111111111111a02222222222222222222222222222222222222222222222222222222222222222a03333333333333333333333333333333333333333333333333333333333333333b90100cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd804d8401c9c380825208846553f10080a04444444444444444444444444444444444444444444444444444444444444444880000000000000000843b9aca00a06666666666666666666666666666666666666666666666666666666666666666";
static const std::string kPreShanghaiHex = "f90201f901fca05555555555555555555555555555555555555555555555555555555555555555a0eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee94ababababababababababababababababababababa01111111111111111111111111111111111111111111111111111111111111111a02222222222222222222222222222222222222222222222222222222222222222a03333333333333333333333333333333333333333333333333333333333333333b90100cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd804d8401c9c380825208846553f10080a04444444444444444444444444444444444444444444444444444444444444444880000000000000000843b9aca00c0c0";       // [header, [], []]
static const std::string kShanghaiHex = "f90245f9021da05555555555555555555555555555555555555555555555555555555555555555a0eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee94ababababababababababababababababababababa01111111111111111111111111111111111111111111111111111111111111111a02222222222222222222222222222222222222222222222222222222222222222a03333333333333333333333333333333333333333333333333333333333333333b90100cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd804d8401c9c380825208846553f10080a04444444444444444444444444444444444444444444444444444444444444444880000000000000000843b9aca00a06666666666666666666666666666666666666666666666666666666666666666c9830102038404050607c0d9d8010294333333333333333333333333333333333333333304";   // [header, [tx1, tx2], [], [w]]
static const std::string kShanghaiEmptyWHex = "f90223f9021da05555555555555555555555555555555555555555555555555555555555555555a0eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee94ababababababababababababababababababababa01111111111111111111111111111111111111111111111111111111111111111a02222222222222222222222222222222222222222222222222222222222222222a03333333333333333333333333333333333333333333333333333333333333333b90100cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd804d8401c9c380825208846553f10080a04444444444444444444444444444444444444444444444444444444444444444880000000000000000843b9aca00a06666666666666666666666666666666666666666666666666666666666666666c0c0c0";  // [header, [], [], []]

static crypto::HashType hashOf(const char* hex8)
{
    // hex8 is a 2-hex-digit byte pattern; repeat 32 times to a full 64-hex-char (32-byte)
    // hash. (8 repetitions would build 8 bytes, which h256 right-aligns to 24 zeros + 8.)
    std::string h = "0x";
    for (int i = 0; i < 32; ++i)
    {
        h += hex8;
    }
    return crypto::HashType(h, crypto::HashType::FromHex);
}

// LONDON header: 16 items (15 required + baseFee). Mirrors /tmp/gen_golden.py header16().
static EthBlockHeaderData makeLondonHeader()
{
    EthBlockHeaderData h;
    h.parentInfo.blockHash = hashOf("55");
    h.uncleHash = hashOf("ee");
    h.coinbase = Address(
        std::string_view("0xabababababababababababababababababababab"), Address::FromHex);
    h.stateRoot = hashOf("11");
    h.txsRoot = hashOf("22");
    h.receiptsRoot = hashOf("33");
    h.logsBloom.fill(0xcd);
    h.difficulty = 0;
    h.number = 77;
    h.gasLimit = 30000000;
    h.gasUsed = 21000;
    h.timestamp = 1700000000;
    h.extraData = {};
    h.prevRandao = hashOf("44");
    h.nonce = h64(std::string_view("0x0000000000000000"), h64::FromHex);
    h.baseFee = 1000000000;
    return h;
}

// SHANGHAI header: 17 items (adds withdrawalsHash).
static EthBlockHeaderData makeShanghaiHeader()
{
    auto h = makeLondonHeader();
    h.withdrawalsHash = hashOf("66");
    return h;
}

static EthWithdrawalData makeWithdrawal()
{
    EthWithdrawalData w;
    w.index = 1;
    w.validatorIndex = 2;
    w.address = Address(
        std::string_view("0x3333333333333333333333333333333333333333"), Address::FromHex);
    w.amount = 4;
    return w;
}

// The EthBlockHeaderData codec overloads are the single source of truth for the header field
// order; EthBlockBody reuses them. Verify they reproduce the reference header RLP exactly.
BOOST_AUTO_TEST_CASE(headerCodecGolden)
{
    auto london = makeLondonHeader();
    bytes out;
    codec::rlp::encode(out, london);
    BOOST_CHECK_EQUAL(toHex(out), kLondonHeaderHex);

    auto shanghai = makeShanghaiHeader();
    bytes out2;
    codec::rlp::encode(out2, shanghai);
    BOOST_CHECK_EQUAL(toHex(out2), kShanghaiHeaderHex);
}

BOOST_AUTO_TEST_CASE(headerCodecRoundTrip)
{
    auto shanghai = makeShanghaiHeader();
    bytes out;
    codec::rlp::encode(out, shanghai);
    EthBlockHeaderData decoded;
    auto mutableData = out;
    bytesRef in(mutableData.data(), mutableData.size());
    BOOST_CHECK(!codec::rlp::decode(in, decoded));
    BOOST_CHECK(decoded == shanghai);
}

BOOST_AUTO_TEST_CASE(goldenEncode)
{
    EthBlockBodyData preShanghai;
    preShanghai.header = makeLondonHeader();
    preShanghai.withdrawals.reset();
    EthBlockBody b(preShanghai);
    bytes out;
    b.rlpEncode(out);
    BOOST_CHECK_EQUAL(toHex(out), kPreShanghaiHex);

    EthBlockBodyData shanghai;
    shanghai.header = makeShanghaiHeader();
    shanghai.transactions = {fromHex("010203"), fromHex("04050607")};
    shanghai.withdrawals = std::vector<EthWithdrawalData>{makeWithdrawal()};
    EthBlockBody b2(shanghai);
    bytes out2;
    b2.rlpEncode(out2);
    BOOST_CHECK_EQUAL(toHex(out2), kShanghaiHex);

    EthBlockBodyData emptyW;
    emptyW.header = makeShanghaiHeader();
    emptyW.withdrawals = std::vector<EthWithdrawalData>{};
    EthBlockBody b3(emptyW);
    bytes out3;
    b3.rlpEncode(out3);
    BOOST_CHECK_EQUAL(toHex(out3), kShanghaiEmptyWHex);
}

BOOST_AUTO_TEST_CASE(goldenDecode)
{
    EthBlockBody b;
    auto rawkPreShanghai = fromHex(kPreShanghaiHex);
    auto err = b.rlpDecode(ref(rawkPreShanghai));
    BOOST_CHECK(!err);
    BOOST_CHECK(b.data().header == makeLondonHeader());
    BOOST_CHECK(b.data().transactions.empty());
    BOOST_CHECK(b.data().ommers.empty());
    BOOST_CHECK(!b.data().withdrawals.has_value());  // pre-Shanghai: field absent

    EthBlockBody b2;
    auto rawkShanghai = fromHex(kShanghaiHex);
    auto err2 = b2.rlpDecode(ref(rawkShanghai));
    BOOST_CHECK(!err2);
    BOOST_CHECK(b2.data().header == makeShanghaiHeader());
    BOOST_REQUIRE_EQUAL(b2.data().transactions.size(), 2u);
    BOOST_CHECK(b2.data().transactions[0] == fromHex("010203"));
    BOOST_CHECK(b2.data().transactions[1] == fromHex("04050607"));
    BOOST_CHECK(b2.data().ommers.empty());
    BOOST_REQUIRE(b2.data().withdrawals.has_value());
    BOOST_REQUIRE_EQUAL(b2.data().withdrawals->size(), 1u);
    BOOST_CHECK((*b2.data().withdrawals)[0] == makeWithdrawal());

    EthBlockBody b3;
    auto rawkShanghaiEmptyW = fromHex(kShanghaiEmptyWHex);
    auto err3 = b3.rlpDecode(ref(rawkShanghaiEmptyW));
    BOOST_CHECK(!err3);
    BOOST_REQUIRE(b3.data().withdrawals.has_value());
    BOOST_CHECK(b3.data().withdrawals->empty());  // Shanghai+: present but empty
}

BOOST_AUTO_TEST_CASE(roundTrip)
{
    EthBlockBodyData body;
    body.header = makeShanghaiHeader();
    body.transactions = {fromHex("010203")};
    body.ommers.push_back(makeLondonHeader());
    body.withdrawals = std::vector<EthWithdrawalData>{makeWithdrawal()};
    EthBlockBody b(body);
    bytes out;
    b.rlpEncode(out);
    EthBlockBody decoded;
    BOOST_CHECK(!decoded.rlpDecode(ref(out)));
    BOOST_CHECK(decoded.data() == body);
}

// Consistency: EthBlockHeader::rlpEncode and the shared EthBlockHeaderData codec must agree.
BOOST_AUTO_TEST_CASE(headerBridgeConsistency)
{
    EthBlockHeaderData data = makeLondonHeader();
    bytes viaCodec;
    codec::rlp::encode(viaCodec, data);

    // Rebuild the same fields through EthBlockHeader (data() is read-only, so construct
    // from a protocol::BlockHeader is not available here; compare via the codec round trip
    // which is what EthBlockHeader::rlpEncode delegates to).
    EthBlockHeaderData decoded;
    auto mutableData = viaCodec;
    bytesRef in(mutableData.data(), mutableData.size());
    BOOST_CHECK(!codec::rlp::decode(in, decoded));
    BOOST_CHECK(decoded == data);
}

BOOST_AUTO_TEST_SUITE_END()
}  // namespace bcos::test
