/**
 *  Copyright (C) 2026 FISCO BCOS.
 *  SPDX-License-Identifier: Apache-2.0
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 * @file EthBlockBodyTest.cpp
 * @brief Golden-vector + round-trip tests for EthBlockBody
 * @date 2026/8/18
 */

#include "bcos-rlp-protocol/EthBlockBody.h"
#include "bcos-rlp-protocol/EthBlockHeader.h"
#include "bcos-rlp-protocol/EthWithdrawal.h"
#include <bcos-utilities/DataConvertUtility.h>
#include <boost/test/unit_test.hpp>

using namespace bcos;
using namespace bcos::protocol;

namespace bcos::test
{
BOOST_AUTO_TEST_SUITE(EthBlockBodyTest)

// Golden vectors generated by an independent Python RLP reference.
static const std::string kLondonHeaderHex =
    "f901fca05555555555555555555555555555555555555555555555555555555555555555a0eeeeeeeeeeeeeeeeeeee"
    "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee94ababababababababababababababababababababa0111111"
    "1111111111111111111111111111111111111111111111111111111111a02222222222222222222222222222222222"
    "222222222222222222222222222222a033333333333333333333333333333333333333333333333333333333333333"
    "33b90100cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
    "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
    "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
    "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
    "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
    "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd804d8401c9c380825208846553f10080a04444444444"
    "444444444444444444444444444444444444444444444444444444880000000000000000843b9aca00";
static const std::string kShanghaiHeaderHex =
    "f9021da05555555555555555555555555555555555555555555555555555555555555555a0eeeeeeeeeeeeeeeeeeee"
    "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee94ababababababababababababababababababababa0111111"
    "1111111111111111111111111111111111111111111111111111111111a02222222222222222222222222222222222"
    "222222222222222222222222222222a033333333333333333333333333333333333333333333333333333333333333"
    "33b90100cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
    "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
    "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
    "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
    "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
    "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd804d8401c9c380825208846553f10080a04444444444"
    "444444444444444444444444444444444444444444444444444444880000000000000000843b9aca00a06666666666"
    "666666666666666666666666666666666666666666666666666666";
static const std::string
    kPreShanghaiHex =
        "f90201f901fca05555555555555555555555555555555555555555555555555555555555555555a0eeeeeeeeee"
        "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee94ababababababababababababababababab"
        "abababa01111111111111111111111111111111111111111111111111111111111111111a02222222222222222"
        "222222222222222222222222222222222222222222222222a03333333333333333333333333333333333333333"
        "333333333333333333333333b90100cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
        "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
        "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
        "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
        "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
        "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
        "cd804d8401c9c380825208846553f10080a0444444444444444444444444444444444444444444444444444444"
        "4444444444880000000000000000843b9aca00c0c0";  // [header, [], []]
static const std::string kShanghaiHex =
    "f90245f9021da05555555555555555555555555555555555555555555555555555555555555555a0eeeeeeeeeeeeee"
    "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee94ababababababababababababababababababababa0"
    "1111111111111111111111111111111111111111111111111111111111111111a02222222222222222222222222222"
    "222222222222222222222222222222222222a033333333333333333333333333333333333333333333333333333333"
    "33333333b90100cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
    "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
    "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
    "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
    "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
    "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd804d8401c9c380825208846553f10080a04444"
    "444444444444444444444444444444444444444444444444444444444444880000000000000000843b9aca00a06666"
    "666666666666666666666666666666666666666666666666666666666666c9830102038404050607c0d9d801029433"
    "3333333333333333333333333333333333333304";  // [header, [tx1, tx2], [], [w]]
static const std::string kShanghaiEmptyWHex =
    "f90223f9021da05555555555555555555555555555555555555555555555555555555555555555a0eeeeeeeeeeeeee"
    "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee94ababababababababababababababababababababa0"
    "1111111111111111111111111111111111111111111111111111111111111111a02222222222222222222222222222"
    "222222222222222222222222222222222222a033333333333333333333333333333333333333333333333333333333"
    "33333333b90100cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
    "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
    "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
    "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
    "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd"
    "cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd804d8401c9c380825208846553f10080a04444"
    "444444444444444444444444444444444444444444444444444444444444880000000000000000843b9aca00a06666"
    "666666666666666666666666666666666666666666666666666666666666c0c0c0";  // [header, [], [], []]

static crypto::HashType hashOf(const char* hex8)
{
    // hex8 is a 2-hex-digit byte pattern; repeat 32 times to a full 64-hex-char (32-byte)
    // hash. (8 repetitions would build 8 bytes, which h256 right-aligns to 24 zeros + 8.)
    std::string h = "0x";
    for (int i = 0; i < 32; ++i)
    {
        h += hex8;
    }
    return crypto::HashType(h, crypto::HashType::FromHex);
}

// LONDON header: 16 items (15 required + baseFee). Mirrors /tmp/gen_golden.py header16().
static EthBlockHeaderData makeLondonHeader()
{
    EthBlockHeaderData h;
    h.parentInfo.blockHash = hashOf("55");
    h.uncleHash = hashOf("ee");
    h.coinbase =
        Address(std::string_view("0xabababababababababababababababababababab"), Address::FromHex);
    h.stateRoot = hashOf("11");
    h.txsRoot = hashOf("22");
    h.receiptsRoot = hashOf("33");
    h.logsBloom.fill(0xcd);
    h.difficulty = 0;
    h.number = 77;
    h.gasLimit = 30000000;
    h.gasUsed = 21000;
    h.timestamp = 1700000000;
    h.extraData = {};
    h.prevRandao = hashOf("44");
    h.nonce = h64(std::string_view("0x0000000000000000"), h64::FromHex);
    h.baseFee = 1000000000;
    return h;
}

// SHANGHAI header: 17 items (adds withdrawalsHash).
static EthBlockHeaderData makeShanghaiHeader()
{
    auto h = makeLondonHeader();
    h.withdrawalsHash = hashOf("66");
    return h;
}

static EthWithdrawalData makeWithdrawal()
{
    EthWithdrawalData w;
    w.index = 1;
    w.validatorIndex = 2;
    w.address =
        Address(std::string_view("0x3333333333333333333333333333333333333333"), Address::FromHex);
    w.amount = 4;
    return w;
}

// The EthBlockHeaderData codec overloads are the single source of truth for the header field
// order; EthBlockBody reuses them. Verify they reproduce the reference header RLP exactly.
BOOST_AUTO_TEST_CASE(headerCodecGolden)
{
    auto london = makeLondonHeader();
    bytes out;
    codec::rlp::encode(out, london);
    BOOST_CHECK_EQUAL(toHex(out), kLondonHeaderHex);

    auto shanghai = makeShanghaiHeader();
    bytes out2;
    codec::rlp::encode(out2, shanghai);
    BOOST_CHECK_EQUAL(toHex(out2), kShanghaiHeaderHex);
}

BOOST_AUTO_TEST_CASE(headerCodecRoundTrip)
{
    auto shanghai = makeShanghaiHeader();
    bytes out;
    codec::rlp::encode(out, shanghai);
    EthBlockHeaderData decoded;
    auto mutableData = out;
    bytesRef in(mutableData.data(), mutableData.size());
    BOOST_CHECK(!codec::rlp::decode(in, decoded));
    BOOST_CHECK(decoded == shanghai);
}

BOOST_AUTO_TEST_CASE(goldenEncode)
{
    EthBlockData preShanghai;
    preShanghai.header = makeLondonHeader();
    preShanghai.withdrawals.reset();
    EthBlock b(preShanghai);
    bytes out;
    b.rlpEncode(out);
    BOOST_CHECK_EQUAL(toHex(out), kPreShanghaiHex);

    EthBlockData shanghai;
    shanghai.header = makeShanghaiHeader();
    shanghai.transactions = {fromHex("010203"), fromHex("04050607")};
    shanghai.withdrawals = std::vector<EthWithdrawalData>{makeWithdrawal()};
    EthBlock b2(shanghai);
    bytes out2;
    b2.rlpEncode(out2);
    BOOST_CHECK_EQUAL(toHex(out2), kShanghaiHex);

    EthBlockData emptyW;
    emptyW.header = makeShanghaiHeader();
    emptyW.withdrawals = std::vector<EthWithdrawalData>{};
    EthBlock b3(emptyW);
    bytes out3;
    b3.rlpEncode(out3);
    BOOST_CHECK_EQUAL(toHex(out3), kShanghaiEmptyWHex);
}

BOOST_AUTO_TEST_CASE(goldenDecode)
{
    EthBlock b;
    auto rawkPreShanghai = fromHex(kPreShanghaiHex);
    auto err = b.rlpDecode(ref(rawkPreShanghai));
    BOOST_CHECK(!err);
    BOOST_CHECK(b.data().header == makeLondonHeader());
    BOOST_CHECK(b.data().transactions.empty());
    BOOST_CHECK(b.data().ommers.empty());
    BOOST_CHECK(!b.data().withdrawals.has_value());  // pre-Shanghai: field absent

    EthBlock b2;
    auto rawkShanghai = fromHex(kShanghaiHex);
    auto err2 = b2.rlpDecode(ref(rawkShanghai));
    BOOST_CHECK(!err2);
    BOOST_CHECK(b2.data().header == makeShanghaiHeader());
    BOOST_REQUIRE_EQUAL(b2.data().transactions.size(), 2u);
    BOOST_CHECK(b2.data().transactions[0] == fromHex("010203"));
    BOOST_CHECK(b2.data().transactions[1] == fromHex("04050607"));
    BOOST_CHECK(b2.data().ommers.empty());
    BOOST_REQUIRE(b2.data().withdrawals.has_value());
    BOOST_REQUIRE_EQUAL(b2.data().withdrawals->size(), 1u);
    BOOST_CHECK((*b2.data().withdrawals)[0] == makeWithdrawal());

    EthBlock b3;
    auto rawkShanghaiEmptyW = fromHex(kShanghaiEmptyWHex);
    auto err3 = b3.rlpDecode(ref(rawkShanghaiEmptyW));
    BOOST_CHECK(!err3);
    BOOST_REQUIRE(b3.data().withdrawals.has_value());
    BOOST_CHECK(b3.data().withdrawals->empty());  // Shanghai+: present but empty
}

BOOST_AUTO_TEST_CASE(roundTrip)
{
    EthBlockData body;
    body.header = makeShanghaiHeader();
    body.transactions = {fromHex("010203")};
    body.ommers.push_back(makeLondonHeader());
    body.withdrawals = std::vector<EthWithdrawalData>{makeWithdrawal()};
    EthBlock b(body);
    bytes out;
    b.rlpEncode(out);
    EthBlock decoded;
    BOOST_CHECK(!decoded.rlpDecode(ref(out)));
    BOOST_CHECK(decoded.data() == body);
}

// A real mainnet legacy transaction (Ethereum wiki canonical example): a 9-field
// RLP list (0xf8...). The body codec must splice it RAW — not re-wrap it as an
// RLP string — and round-trip it byte-identically.
BOOST_AUTO_TEST_CASE(legacyTxGolden)
{
    auto legacyTx = fromHex(
        "f86c808504a817c800825208943535353535353535353535353535353535353535880de0b6b3a764000080"
        "25a028ef61340bd939bc2195fe537567866003e1a15d3c71ff63e1590620aa636276"
        "a067cbe9d8997f761aecb703304b3800ccf555c9f3dc64214b297fb1966a3b6d83");
    BOOST_REQUIRE_EQUAL(legacyTx.front(), 0xf8);  // a list, not a string

    EthBlockData body;
    body.header = makeLondonHeader();
    body.transactions = {legacyTx};
    EthBlock b(body);
    bytes out;
    b.rlpEncode(out);

    EthBlock decoded;
    BOOST_CHECK(!decoded.rlpDecode(ref(out)));
    BOOST_REQUIRE_EQUAL(decoded.data().transactions.size(), 1u);
    // Byte-identical: the legacy list header must survive encode+decode untouched.
    BOOST_CHECK(decoded.data().transactions[0] == legacyTx);
    BOOST_CHECK(decoded.data() == body);
}

// Mixed legacy (raw list) + typed (string-wrapped) transactions round-trip.
BOOST_AUTO_TEST_CASE(legacyAndTypedMixedRoundTrip)
{
    auto legacyTx = fromHex(
        "f86c808504a817c800825208943535353535353535353535353535353535353535880de0b6b3a764000080"
        "25a028ef61340bd939bc2195fe537567866003e1a15d3c71ff63e1590620aa636276"
        "a067cbe9d8997f761aecb703304b3800ccf555c9f3dc64214b297fb1966a3b6d83");
    // Real Sepolia EIP-1559 (type 0x02) transfer.
    auto typedTx = fromHex(
        "02f87783aa36a7808459682f00851f71a335b5825208942f14582947e292a2ecd20c430b46f2"
        "d27cfe213c8901a055690d9db8000080c080a06dd8b58b520530663fa1ce8bbbc3eb9b2e0b79"
        "70138d781b9d9380e3dbf1f362a0098934613bfad8e42b3d93b26b450d1028c2288e212c8160"
        "5a54d886028c5746");

    EthBlockData body;
    body.header = makeShanghaiHeader();
    body.transactions = {legacyTx, typedTx};
    body.withdrawals = std::vector<EthWithdrawalData>{};
    EthBlock b(body);
    bytes out;
    b.rlpEncode(out);
    EthBlock decoded;
    BOOST_CHECK(!decoded.rlpDecode(ref(out)));
    BOOST_REQUIRE_EQUAL(decoded.data().transactions.size(), 2u);
    BOOST_CHECK(decoded.data().transactions[0] == legacyTx);
    BOOST_CHECK(decoded.data().transactions[1] == typedTx);
    BOOST_CHECK(decoded.data() == body);
}

// A typed transaction whose content starts with the reserved type byte 0x00 must
// be rejected (geth: errTxTypeNotSupported).
BOOST_AUTO_TEST_CASE(rejectsReservedTypeByte)
{
    EthBlockData body;
    body.header = makeLondonHeader();
    body.transactions = {fromHex("0080")};  // 0x00 || rlp(empty payload)
    EthBlock b(body);
    bytes out;
    b.rlpEncode(out);
    EthBlock decoded;
    BOOST_CHECK(decoded.rlpDecode(ref(out)) != nullptr);
}

// A 5-element body [header, txs, ommers, withdrawals, extra] must be rejected
// (geth's Block.DecodeRLP calls ListEnd and rejects the surplus).
BOOST_AUTO_TEST_CASE(rejectsTrailingElements)
{
    bytes headerRlp;
    codec::rlp::encode(headerRlp, makeLondonHeader());
    bytes const txs = {0xc0};     // empty transactions list
    bytes const ommers = {0xc0};  // empty ommers list
    bytes const wd = {0xc0};      // empty withdrawals list
    bytes const extra = {0xc0};   // surplus element

    bytes wire;
    codec::rlp::encodeHeader(wire, {.isList = true,
                                       .payloadLength = headerRlp.size() + txs.size() +
                                                        ommers.size() + wd.size() + extra.size()});
    wire.insert(wire.end(), headerRlp.begin(), headerRlp.end());
    wire.insert(wire.end(), txs.begin(), txs.end());
    wire.insert(wire.end(), ommers.begin(), ommers.end());
    wire.insert(wire.end(), wd.begin(), wd.end());
    wire.insert(wire.end(), extra.begin(), extra.end());

    EthBlock decoded;
    BOOST_CHECK(decoded.rlpDecode(ref(wire)) != nullptr);
}

BOOST_AUTO_TEST_SUITE_END()
}  // namespace bcos::test
