/**
 *  Copyright (C) 2026 FISCO BCOS.
 *  SPDX-License-Identifier: Apache-2.0
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 * @file EthLogTest.cpp
 * @brief Golden-vector + round-trip tests for EthLog
 * @date 2026/8/18
 */

#include "bcos-rlp-protocol/EthLog.h"
#include <bcos-utilities/DataConvertUtility.h>
#include <boost/test/unit_test.hpp>

using namespace bcos;
using namespace bcos::protocol;

namespace bcos::test
{
BOOST_AUTO_TEST_SUITE(EthLogTest)

// Golden vectors generated by an independent Python RLP reference (see /tmp/gen_golden.py).
// log1 = rlp([0x11*20, [0x22*32], 0xdeadbeef])
static const std::string kLog1Hex =
    "f83c941111111111111111111111111111111111111111e1a022222222222222222222222222222222222222222222"
    "2222222222222222222284deadbeef";
// log2 = rlp([0xff*20, [0xaa*32, 0xbb*32], ""])
static const std::string kLog2Hex =
    "f85a94fffffffffffffffffffffffffffffffffffffffff842a0aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    "aaaaaaaaaaaaaaaaaaaaaaa0bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb80";

static EthLogData makeLog1()
{
    EthLogData log;
    log.address =
        Address(std::string_view("0x1111111111111111111111111111111111111111"), Address::FromHex);
    log.topics.push_back(crypto::HashType(
        std::string_view("0x2222222222222222222222222222222222222222222222222222222222222222"),
        crypto::HashType::FromHex));
    log.data = fromHex("deadbeef");
    return log;
}

static EthLogData makeLog2()
{
    EthLogData log;
    log.address =
        Address(std::string_view("0xffffffffffffffffffffffffffffffffffffffff"), Address::FromHex);
    log.topics.push_back(crypto::HashType(
        std::string_view("0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"),
        crypto::HashType::FromHex));
    log.topics.push_back(crypto::HashType(
        std::string_view("0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"),
        crypto::HashType::FromHex));
    return log;
}

BOOST_AUTO_TEST_CASE(goldenEncode)
{
    EthLog ethLog(makeLog1());
    bytes out;
    ethLog.rlpEncode(out);
    BOOST_CHECK_EQUAL(toHex(out), kLog1Hex);

    EthLog ethLog2(makeLog2());
    bytes out2;
    ethLog2.rlpEncode(out2);
    BOOST_CHECK_EQUAL(toHex(out2), kLog2Hex);
}

BOOST_AUTO_TEST_CASE(goldenDecode)
{
    EthLog ethLog;
    auto rawkLog1 = fromHex(kLog1Hex);
    auto err = ethLog.rlpDecode(ref(rawkLog1));
    BOOST_CHECK(!err);
    BOOST_CHECK(ethLog.data() == makeLog1());

    EthLog ethLog2;
    auto rawkLog2 = fromHex(kLog2Hex);
    auto err2 = ethLog2.rlpDecode(ref(rawkLog2));
    BOOST_CHECK(!err2);
    BOOST_CHECK(ethLog2.data() == makeLog2());
}

BOOST_AUTO_TEST_CASE(roundTrip)
{
    auto log = makeLog1();
    EthLog ethLog(log);
    bytes out;
    ethLog.rlpEncode(out);
    EthLog decoded;
    BOOST_CHECK(!decoded.rlpDecode(ref(out)));
    BOOST_CHECK(decoded.data() == log);
}

// Trailing bytes after the top-level RLP item must be rejected (round-6 F3 guard).
BOOST_AUTO_TEST_CASE(rlpDecodeRejectsTrailingBytes)
{
    auto log = makeLog1();
    EthLog ethLog(log);
    bytes out;
    ethLog.rlpEncode(out);
    out.push_back(0xff);
    EthLog decoded;
    BOOST_REQUIRE(decoded.rlpDecode(ref(out)) != nullptr);
}

// std::vector<EthLogData> through the generic list codec (used by EthReceipt).
BOOST_AUTO_TEST_CASE(vectorRoundTrip)
{
    std::vector<EthLogData> logs = {makeLog1(), makeLog2()};
    bytes out;
    codec::rlp::encode(out, logs);
    std::vector<EthLogData> decoded;
    auto mutableData = out;
    bytesRef in(mutableData.data(), mutableData.size());
    BOOST_CHECK(!codec::rlp::decode(in, decoded));
    BOOST_CHECK(decoded == logs);
}

BOOST_AUTO_TEST_CASE(malformedRejected)
{
    // 0x80 (empty string) is not a log list.
    EthLog ethLog;
    auto rawMalformed1 = fromHex("80");
    auto err = ethLog.rlpDecode(ref(rawMalformed1));
    BOOST_CHECK(err != nullptr);
    // A two-element list is missing the data field (decode succeeds? no: the variadic list
    // decode requires exactly 3 items, so a 2-item list leaves the view non-empty -> error).
    auto rawMalformed2 = fromHex("d60194999999999999999999999999999999999999999980");
    auto err2 = ethLog.rlpDecode(ref(rawMalformed2));
    BOOST_CHECK(err2 != nullptr);
}

BOOST_AUTO_TEST_SUITE_END()
}  // namespace bcos::test
