/**
 *  Copyright (C) 2026 FISCO BCOS.
 *  SPDX-License-Identifier: Apache-2.0
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 * @file EthReceiptTest.cpp
 * @brief Golden-vector + round-trip tests for EthReceipt
 * @date 2026/8/18
 */

#include "bcos-rlp-protocol/EthLog.h"
#include "bcos-rlp-protocol/EthReceipt.h"
#include <bcos-protocol/TransactionStatus.h>
#include <bcos-tars-protocol/protocol/TransactionReceiptImpl.h>
#include <bcos-tars-protocol/tars/Block.h>
#include <bcos-utilities/DataConvertUtility.h>
#include <boost/test/unit_test.hpp>

using namespace bcos;
using namespace bcos::protocol;

namespace bcos::test
{
BOOST_AUTO_TEST_SUITE(EthReceiptTest)

// Golden vectors generated by an independent Python RLP reference.
static const std::string kTyped2Hex = "02f9010801825208b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0";    // 0x02 || rlp([1, 21000, bloom0, []])
static const std::string kTyped1Hex = "01f901470182c350b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f83ef83c941111111111111111111111111111111111111111e1a0222222222222222222222222222222222222222222222222222222222222222284deadbeef";    // 0x01 || rlp([1, 50000, bloom0, [log1]])
static const std::string kLegacyHex = "f901068080b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0";    // rlp([0, 0, bloom0, []])
static const std::string kPostStateHex = "f90129a05555555555555555555555555555555555555555555555555555555555555555830186a0b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0";  // rlp([0x55*32, 100000, bloom0, []])
static const std::string kTyped3Hex = "03f9010801825208b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0";    // 0x03 || rlp([1, 21000, bloom0, []])

static bcos::Bloom makeBloom()
{
    bcos::Bloom bloom{};
    bloom.fill(0);  // 256 zero bytes
    return bloom;
}

static EthLogData makeLog1()
{
    EthLogData log;
    log.address = Address(
        std::string_view("0x1111111111111111111111111111111111111111"), Address::FromHex);
    log.topics.push_back(crypto::HashType(
        std::string_view("0x2222222222222222222222222222222222222222222222222222222222222222"),
        crypto::HashType::FromHex));
    log.data = fromHex("deadbeef");
    return log;
}

BOOST_AUTO_TEST_CASE(goldenEncode)
{
    EthReceiptData typed2;
    typed2.type = 2;
    typed2.status = 1;
    typed2.cumulativeGasUsed = 21000;
    typed2.logsBloom = makeBloom();
    EthReceipt r(typed2);
    bytes out;
    r.rlpEncode(out);
    BOOST_CHECK_EQUAL(toHex(out), kTyped2Hex);

    EthReceiptData typed1 = typed2;
    typed1.type = 1;
    typed1.cumulativeGasUsed = 50000;
    typed1.logs.push_back(makeLog1());
    EthReceipt r1(typed1);
    bytes out1;
    r1.rlpEncode(out1);
    BOOST_CHECK_EQUAL(toHex(out1), kTyped1Hex);

    EthReceiptData legacy;
    legacy.type = 0;
    legacy.status = 0;
    EthReceipt rl(legacy);
    bytes outl;
    rl.rlpEncode(outl);
    BOOST_CHECK_EQUAL(toHex(outl), kLegacyHex);

    EthReceiptData postState;
    postState.type = 0;
    postState.postState = crypto::HashType(
        std::string_view("0x5555555555555555555555555555555555555555555555555555555555555555"),
        crypto::HashType::FromHex);
    postState.cumulativeGasUsed = 100000;
    EthReceipt rp(postState);
    bytes outp;
    rp.rlpEncode(outp);
    BOOST_CHECK_EQUAL(toHex(outp), kPostStateHex);

    EthReceiptData typed3 = typed2;
    typed3.type = 3;
    EthReceipt r3(typed3);
    bytes out3;
    r3.rlpEncode(out3);
    BOOST_CHECK_EQUAL(toHex(out3), kTyped3Hex);
}

BOOST_AUTO_TEST_CASE(goldenDecode)
{
    EthReceipt r;
    auto rawkTyped2 = fromHex(kTyped2Hex);
    auto err = r.rlpDecode(ref(rawkTyped2));
    BOOST_CHECK(!err);
    BOOST_CHECK_EQUAL(r.data().type, 2);
    BOOST_CHECK_EQUAL(r.data().status, 1);
    BOOST_CHECK_EQUAL(r.data().cumulativeGasUsed, u256(21000));
    BOOST_CHECK(!r.data().postState.has_value());
    BOOST_CHECK(r.data().logs.empty());
    BOOST_CHECK(r.data().logsBloom == makeBloom());

    EthReceipt rl;
    auto rawkLegacy = fromHex(kLegacyHex);
    auto errl = rl.rlpDecode(ref(rawkLegacy));
    BOOST_CHECK(!errl);
    BOOST_CHECK_EQUAL(rl.data().type, 0);
    BOOST_CHECK_EQUAL(rl.data().status, 0);
    BOOST_CHECK(!rl.data().postState.has_value());
    BOOST_CHECK(rl.data().logs.empty());

    EthReceipt rp;
    auto rawkPostState = fromHex(kPostStateHex);
    auto errp = rp.rlpDecode(ref(rawkPostState));
    BOOST_CHECK(!errp);
    BOOST_CHECK_EQUAL(rp.data().type, 0);
    BOOST_CHECK(rp.data().postState.has_value());
    BOOST_CHECK_EQUAL(rp.data().cumulativeGasUsed, u256(100000));
    BOOST_CHECK(rp.data().logs.empty());

    EthReceipt r1;
    auto rawkTyped1 = fromHex(kTyped1Hex);
    auto err1 = r1.rlpDecode(ref(rawkTyped1));
    BOOST_CHECK(!err1);
    BOOST_CHECK_EQUAL(r1.data().type, 1);
    BOOST_CHECK_EQUAL(r1.data().logs.size(), 1u);
    BOOST_CHECK(r1.data().logs[0] == makeLog1());
}

BOOST_AUTO_TEST_CASE(roundTrip)
{
    EthReceiptData typed2;
    typed2.type = 2;
    typed2.status = 1;
    typed2.cumulativeGasUsed = 21000;
    typed2.logsBloom = makeBloom();
    typed2.logs.push_back(makeLog1());
    EthReceipt r(typed2);
    bytes out;
    r.rlpEncode(out);
    EthReceipt decoded;
    BOOST_CHECK(!decoded.rlpDecode(ref(out)));
    BOOST_CHECK(decoded.data() == typed2);
}

BOOST_AUTO_TEST_CASE(malformedRejected)
{
    // A type-prefixed receipt whose inner list is empty (no status/cumGas/bloom/logs) is
    // structurally malformed: the 4-item list decode fails with InputTooShort.
    EthReceipt r;
    auto rawMalformed1 = fromHex("05c0");
    auto err = r.rlpDecode(ref(rawMalformed1));
    BOOST_CHECK(err != nullptr);

    // A legacy receipt list that is truncated after the first (postState) item.
    auto rawMalformed2 = fromHex("f5a05555555555555555555555555555555555555555555555555555555555555555");
    auto err3 = r.rlpDecode(ref(rawMalformed2));
    BOOST_CHECK(err3 != nullptr);

    // Empty input.
    auto rawMalformed3 = fromHex("");
    auto err2 = r.rlpDecode(ref(rawMalformed3));
    BOOST_CHECK(err2 != nullptr);
}

// toEthReceiptData: BCOS receipt (FISCO TransactionStatus) -> Ethereum receipt data
// (EIP-658 status 0/1, tx type, cumulative gas, bloom, logs) — the receiptsRoot trie value.
BOOST_AUTO_TEST_CASE(toEthReceiptDataConversion)
{
    auto receipt = std::make_shared<bcostars::protocol::TransactionReceiptImpl>();
    auto& inner = receipt->inner();
    inner.data.status = 0;  // TransactionStatus::None == success
    inner.data.gasUsed = "21000";
    inner.cumulativeGasUsed = "42000";  // second tx in block
    inner.logsBloom.assign(256, static_cast<char>(0xab));

    bcostars::LogEntry tarsLog;
    tarsLog.address = std::string(20, static_cast<char>(0x11));
    tarsLog.topic.push_back(std::vector<char>(32, static_cast<char>(0x22)));
    tarsLog.data = {static_cast<char>(0xde), static_cast<char>(0xad)};
    inner.data.logEntries.push_back(std::move(tarsLog));

    auto eth = protocol::toEthReceiptData(*receipt, 2);  // EIP-1559

    BOOST_CHECK_EQUAL(eth.type, 2);
    BOOST_CHECK_EQUAL(eth.status, 1);  // None -> EIP-658 success
    BOOST_CHECK_EQUAL(eth.cumulativeGasUsed, u256(42000));
    BOOST_CHECK(eth.logsBloom[0] == 0xab && eth.logsBloom[255] == 0xab);
    BOOST_REQUIRE_EQUAL(eth.logs.size(), 1u);
    BOOST_CHECK_EQUAL(eth.logs[0].address,
        Address(std::string_view("0x1111111111111111111111111111111111111111"),
            Address::FromHex));
    BOOST_REQUIRE_EQUAL(eth.logs[0].topics.size(), 1u);
    BOOST_CHECK_EQUAL(eth.logs[0].topics[0],
        crypto::HashType(
            std::string_view("0x2222222222222222222222222222222222222222222222222222222222222222"),
            crypto::HashType::FromHex));
    BOOST_CHECK(eth.logs[0].data == fromHex("dead"));

    // Failure status maps to EIP-658 0.
    inner.data.status = static_cast<int32_t>(TransactionStatus::RevertInstruction);
    auto ethFail = protocol::toEthReceiptData(*receipt, 1);
    BOOST_CHECK_EQUAL(ethFail.status, 0);
    BOOST_CHECK_EQUAL(ethFail.type, 1);
}

BOOST_AUTO_TEST_SUITE_END()
}  // namespace bcos::test
