/**
 *  Copyright (C) 2026 FISCO BCOS.
 *  SPDX-License-Identifier: Apache-2.0
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 * @file EthReceiptTest.cpp
 * @brief Golden-vector + round-trip tests for EthReceipt
 * @date 2026/8/18
 */

#include "bcos-rlp-protocol/EthReceipt.h"
#include "bcos-rlp-protocol/EthLog.h"
#include <bcos-protocol/TransactionStatus.h>
#include <bcos-tars-protocol/protocol/TransactionReceiptImpl.h>
#include <bcos-tars-protocol/tars/Block.h>
#include <bcos-utilities/DataConvertUtility.h>
#include <boost/test/unit_test.hpp>

using namespace bcos;
using namespace bcos::protocol;

namespace bcos::test
{
BOOST_AUTO_TEST_SUITE(EthReceiptTest)

// Golden vectors generated by an independent Python RLP reference.
static const std::string kTyped2Hex =
    "02f9010801825208b90100000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000c0";  // 0x02 || rlp([1, 21000,
                                                                           // bloom0, []])
static const std::string kTyped1Hex =
    "01f901470182c350b90100000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000f83ef83c9411111111111111111111"
    "11111111111111111111e1a0222222222222222222222222222222222222222222222222222222222222222284dead"
    "beef";  // 0x01 || rlp([1, 50000, bloom0, [log1]])
static const std::string kLegacyHex =
    "f901068080b90100000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000c0";  // rlp([0, 0, bloom0, []])
static const std::string kPostStateHex =
    "f90129a05555555555555555555555555555555555555555555555555555555555555555830186a0b9010000000000"
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000c0";  // rlp([0x55*32, 100000, bloom0, []])
static const std::string kTyped3Hex =
    "03f9010801825208b90100000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "0000000000000000000000000000000000000000000000000000000000000000c0";  // 0x03 || rlp([1, 21000,
                                                                           // bloom0, []])

static bcos::Bloom makeBloom()
{
    bcos::Bloom bloom{};
    bloom.fill(0);  // 256 zero bytes
    return bloom;
}

static EthLogData makeLog1()
{
    EthLogData log;
    log.address =
        Address(std::string_view("0x1111111111111111111111111111111111111111"), Address::FromHex);
    log.topics.push_back(crypto::HashType(
        std::string_view("0x2222222222222222222222222222222222222222222222222222222222222222"),
        crypto::HashType::FromHex));
    log.data = fromHex("deadbeef");
    return log;
}

BOOST_AUTO_TEST_CASE(goldenEncode)
{
    EthReceiptData typed2;
    typed2.type = 2;
    typed2.status = 1;
    typed2.cumulativeGasUsed = 21000;
    typed2.logsBloom = makeBloom();
    EthReceipt r(typed2);
    bytes out;
    BOOST_REQUIRE(!r.rlpEncode(out));
    BOOST_CHECK_EQUAL(toHex(out), kTyped2Hex);

    EthReceiptData typed1 = typed2;
    typed1.type = 1;
    typed1.cumulativeGasUsed = 50000;
    typed1.logs.push_back(makeLog1());
    EthReceipt r1(typed1);
    bytes out1;
    BOOST_REQUIRE(!r1.rlpEncode(out1));
    BOOST_CHECK_EQUAL(toHex(out1), kTyped1Hex);

    EthReceiptData legacy;
    legacy.type = 0;
    legacy.status = 0;
    EthReceipt rl(legacy);
    bytes outl;
    BOOST_REQUIRE(!rl.rlpEncode(outl));
    BOOST_CHECK_EQUAL(toHex(outl), kLegacyHex);

    EthReceiptData postState;
    postState.type = 0;
    postState.postState = crypto::HashType(
        std::string_view("0x5555555555555555555555555555555555555555555555555555555555555555"),
        crypto::HashType::FromHex);
    postState.cumulativeGasUsed = 100000;
    EthReceipt rp(postState);
    bytes outp;
    BOOST_REQUIRE(!rp.rlpEncode(outp));
    BOOST_CHECK_EQUAL(toHex(outp), kPostStateHex);

    EthReceiptData typed3 = typed2;
    typed3.type = 3;
    EthReceipt r3(typed3);
    bytes out3;
    BOOST_REQUIRE(!r3.rlpEncode(out3));
    BOOST_CHECK_EQUAL(toHex(out3), kTyped3Hex);
}

BOOST_AUTO_TEST_CASE(goldenDecode)
{
    EthReceipt r;
    auto rawkTyped2 = fromHex(kTyped2Hex);
    auto err = r.rlpDecode(ref(rawkTyped2));
    BOOST_CHECK(!err);
    BOOST_CHECK_EQUAL(r.data().type, 2);
    BOOST_CHECK_EQUAL(r.data().status, 1);
    BOOST_CHECK_EQUAL(r.data().cumulativeGasUsed, u256(21000));
    BOOST_CHECK(!r.data().postState.has_value());
    BOOST_CHECK(r.data().logs.empty());
    BOOST_CHECK(r.data().logsBloom == makeBloom());

    EthReceipt rl;
    auto rawkLegacy = fromHex(kLegacyHex);
    auto errl = rl.rlpDecode(ref(rawkLegacy));
    BOOST_CHECK(!errl);
    BOOST_CHECK_EQUAL(rl.data().type, 0);
    BOOST_CHECK_EQUAL(rl.data().status, 0);
    BOOST_CHECK(!rl.data().postState.has_value());
    BOOST_CHECK(rl.data().logs.empty());

    EthReceipt rp;
    auto rawkPostState = fromHex(kPostStateHex);
    auto errp = rp.rlpDecode(ref(rawkPostState));
    BOOST_CHECK(!errp);
    BOOST_CHECK_EQUAL(rp.data().type, 0);
    BOOST_CHECK(rp.data().postState.has_value());
    BOOST_CHECK_EQUAL(rp.data().cumulativeGasUsed, u256(100000));
    BOOST_CHECK(rp.data().logs.empty());

    EthReceipt r1;
    auto rawkTyped1 = fromHex(kTyped1Hex);
    auto err1 = r1.rlpDecode(ref(rawkTyped1));
    BOOST_CHECK(!err1);
    BOOST_CHECK_EQUAL(r1.data().type, 1);
    BOOST_CHECK_EQUAL(r1.data().logs.size(), 1u);
    BOOST_CHECK(r1.data().logs[0] == makeLog1());
}

BOOST_AUTO_TEST_CASE(roundTrip)
{
    EthReceiptData typed2;
    typed2.type = 2;
    typed2.status = 1;
    typed2.cumulativeGasUsed = 21000;
    typed2.logsBloom = makeBloom();
    typed2.logs.push_back(makeLog1());
    EthReceipt r(typed2);
    bytes out;
    BOOST_REQUIRE(!r.rlpEncode(out));
    EthReceipt decoded;
    BOOST_CHECK(!decoded.rlpDecode(ref(out)));
    BOOST_CHECK(decoded.data() == typed2);
}

// Trailing bytes after the top-level RLP item must be rejected (round-6 F3 guard).
BOOST_AUTO_TEST_CASE(rlpDecodeRejectsTrailingBytes)
{
    EthReceiptData typed2;
    typed2.type = 2;
    typed2.status = 1;
    typed2.cumulativeGasUsed = 21000;
    typed2.logsBloom = makeBloom();
    typed2.logs.push_back(makeLog1());
    EthReceipt r(typed2);
    bytes out;
    BOOST_REQUIRE(!r.rlpEncode(out));
    out.push_back(0xff);
    EthReceipt decoded;
    BOOST_REQUIRE(decoded.rlpDecode(ref(out)) != nullptr);
}

// A receipt with a type byte >= 0x80 must be rejected by the encoder (the decoder
// would misread it as a legacy RLP item head).
BOOST_AUTO_TEST_CASE(rlpEncodeRejectsBadType)
{
    EthReceiptData data;
    data.type = 0x80;
    data.status = 1;
    data.cumulativeGasUsed = 21000;
    data.logsBloom = makeBloom();
    EthReceipt r(data);
    bytes out;
    BOOST_REQUIRE(r.rlpEncode(out) != nullptr);
}

BOOST_AUTO_TEST_CASE(malformedRejected)
{
    // A type-prefixed receipt whose inner list is empty (no status/cumGas/bloom/logs) is
    // structurally malformed: the 4-item list decode fails with InputTooShort.
    EthReceipt r;
    auto rawMalformed1 = fromHex("05c0");
    auto err = r.rlpDecode(ref(rawMalformed1));
    BOOST_CHECK(err != nullptr);

    // A legacy receipt list that is truncated after the first (postState) item.
    auto rawMalformed2 =
        fromHex("f5a05555555555555555555555555555555555555555555555555555555555555555");
    auto err3 = r.rlpDecode(ref(rawMalformed2));
    BOOST_CHECK(err3 != nullptr);

    // Empty input.
    auto rawMalformed3 = fromHex("");
    auto err2 = r.rlpDecode(ref(rawMalformed3));
    BOOST_CHECK(err2 != nullptr);

    // Legacy receipt with an invalid single-byte status (0x02): geth rejects all
    // but 0x01 / empty / 32-byte postState.
    auto rawBadStatus = fromHex("c402808080");
    auto errBad = r.rlpDecode(ref(rawBadStatus));
    BOOST_CHECK(errBad != nullptr);
    // status byte 0x80 (canonical 81 80) also rejected.
    auto rawBadStatus2 = fromHex("c58180808080");
    auto errBad2 = r.rlpDecode(ref(rawBadStatus2));
    BOOST_CHECK(errBad2 != nullptr);
}

// A legacy receipt with status byte 0x01 (EIP-658 success) decodes with status 1.
BOOST_AUTO_TEST_CASE(legacyReceiptStatusOne)
{
    EthReceiptData data;
    data.type = 0;
    data.status = 1;
    data.cumulativeGasUsed = 21000;
    data.logsBloom = makeBloom();
    EthReceipt r(data);
    bytes out;
    BOOST_REQUIRE(!r.rlpEncode(out));
    EthReceipt decoded;
    BOOST_REQUIRE(!decoded.rlpDecode(ref(out)));
    BOOST_CHECK_EQUAL(decoded.data().status, 1);
}

// toEthReceiptData: BCOS receipt (FISCO TransactionStatus) -> Ethereum receipt data
// (EIP-658 status 0/1, tx type, cumulative gas, bloom, logs) — the receiptsRoot trie value.
BOOST_AUTO_TEST_CASE(toEthReceiptDataConversion)
{
    auto receipt = std::make_shared<bcostars::protocol::TransactionReceiptImpl>();
    auto& inner = receipt->inner();
    inner.data.status = 0;  // TransactionStatus::None == success
    inner.data.gasUsed = "21000";
    inner.cumulativeGasUsed = "42000";  // second tx in block
    inner.logsBloom.assign(256, static_cast<char>(0xab));

    bcostars::LogEntry tarsLog;
    // In-tree producers (HostContext) store the address as 40 ASCII hex chars.
    tarsLog.address = std::string(40, '1');  // -> 20 raw bytes of 0x11
    tarsLog.topic.push_back(std::vector<char>(32, static_cast<char>(0x22)));
    tarsLog.data = {static_cast<char>(0xde), static_cast<char>(0xad)};
    inner.data.logEntries.push_back(std::move(tarsLog));

    protocol::EthReceiptData eth;
    BOOST_REQUIRE(!protocol::toEthReceiptData(*receipt, 2, eth));  // EIP-1559

    BOOST_CHECK_EQUAL(eth.type, 2);
    BOOST_CHECK_EQUAL(eth.status, 1);  // None -> EIP-658 success
    BOOST_CHECK_EQUAL(eth.cumulativeGasUsed, u256(42000));
    BOOST_CHECK(eth.logsBloom[0] == 0xab && eth.logsBloom[255] == 0xab);
    BOOST_REQUIRE_EQUAL(eth.logs.size(), 1u);
    BOOST_CHECK_EQUAL(eth.logs[0].address,
        Address(std::string_view("0x1111111111111111111111111111111111111111"), Address::FromHex));
    BOOST_REQUIRE_EQUAL(eth.logs[0].topics.size(), 1u);
    BOOST_CHECK_EQUAL(eth.logs[0].topics[0],
        crypto::HashType(
            std::string_view("0x2222222222222222222222222222222222222222222222222222222222222222"),
            crypto::HashType::FromHex));
    BOOST_CHECK(eth.logs[0].data == fromHex("dead"));

    // Failure status maps to EIP-658 0.
    inner.data.status = static_cast<int32_t>(TransactionStatus::RevertInstruction);
    protocol::EthReceiptData ethFail;
    BOOST_REQUIRE(!protocol::toEthReceiptData(*receipt, 1, ethFail));
    BOOST_CHECK_EQUAL(ethFail.status, 0);
    BOOST_CHECK_EQUAL(ethFail.type, 1);
}

// Fail closed: a logsBloom of the wrong size must be rejected, not silently substituted,
// because the value feeds the receiptsRoot trie.
BOOST_AUTO_TEST_CASE(toEthReceiptDataFailClosedBloom)
{
    auto receipt = std::make_shared<bcostars::protocol::TransactionReceiptImpl>();
    auto& inner = receipt->inner();
    inner.data.status = 0;
    inner.data.gasUsed = "21000";
    inner.cumulativeGasUsed = "42000";
    inner.logsBloom.assign(32, static_cast<char>(0xab));  // wrong size (not 256)

    protocol::EthReceiptData eth;
    BOOST_REQUIRE(protocol::toEthReceiptData(*receipt, 1, eth) != nullptr);
}

// An out-of-range EIP-2718 type byte (>= 0x80) must be rejected, not written as a
// prefix that would be read back as a legacy RLP item head.
BOOST_AUTO_TEST_CASE(toEthReceiptDataRejectsBadType)
{
    auto receipt = std::make_shared<bcostars::protocol::TransactionReceiptImpl>();
    auto& inner = receipt->inner();
    inner.data.status = 0;
    inner.data.gasUsed = "21000";
    inner.cumulativeGasUsed = "42000";
    inner.logsBloom.assign(256, static_cast<char>(0xab));
    protocol::EthReceiptData eth;
    BOOST_REQUIRE(protocol::toEthReceiptData(*receipt, 0x80, eth) != nullptr);
}

// The log-address conversion must accept 20 raw bytes and reject invalid lengths
// (regression for the round-8 HIGH AlignRight-truncation fix, which was only
// exercised on the 40-hex branch).
BOOST_AUTO_TEST_CASE(logAddressRawAndInvalidLength)
{
    // 20 raw bytes -> copied directly (0x11 x 20).
    {
        auto receipt = std::make_shared<bcostars::protocol::TransactionReceiptImpl>();
        auto& inner = receipt->inner();
        inner.data.status = 0;
        inner.data.gasUsed = "21000";
        inner.cumulativeGasUsed = "42000";
        inner.logsBloom.assign(256, static_cast<char>(0xab));
        bcostars::LogEntry tarsLog;
        tarsLog.address = std::string(20, static_cast<char>(0x11));
        inner.data.logEntries.push_back(std::move(tarsLog));
        protocol::EthReceiptData eth;
        BOOST_REQUIRE(!protocol::toEthReceiptData(*receipt, 1, eth));
        BOOST_REQUIRE_EQUAL(eth.logs.size(), 1u);
        bcos::bytes const expected(20, static_cast<bcos::byte>(0x11));
        BOOST_CHECK(
            eth.logs[0].address == Address(bcos::bytesConstRef(expected.data(), expected.size())));
    }
    // Invalid length (30) -> fail closed.
    {
        auto receipt = std::make_shared<bcostars::protocol::TransactionReceiptImpl>();
        auto& inner = receipt->inner();
        inner.data.status = 0;
        inner.data.gasUsed = "21000";
        inner.cumulativeGasUsed = "42000";
        inner.logsBloom.assign(256, static_cast<char>(0xab));
        bcostars::LogEntry tarsLog;
        tarsLog.address = std::string(30, 'x');
        inner.data.logEntries.push_back(std::move(tarsLog));
        protocol::EthReceiptData eth;
        BOOST_REQUIRE(protocol::toEthReceiptData(*receipt, 1, eth) != nullptr);
    }
}

// Fail closed: a malformed cumulativeGasUsed must be rejected, not substituted,
// because the value feeds the receipts root; the 0x-prefixed hex producer form
// (opstack-executor) must parse.
BOOST_AUTO_TEST_CASE(toEthReceiptDataFailClosedGas)
{
    // Empty cumulativeGasUsed.
    {
        auto receipt = std::make_shared<bcostars::protocol::TransactionReceiptImpl>();
        auto& inner = receipt->inner();
        inner.data.status = 0;
        inner.data.gasUsed = "21000";
        inner.cumulativeGasUsed = "";
        inner.logsBloom.assign(256, static_cast<char>(0xab));
        protocol::EthReceiptData eth;
        BOOST_REQUIRE(protocol::toEthReceiptData(*receipt, 1, eth) != nullptr);
    }
    // Non-numeric cumulativeGasUsed.
    {
        auto receipt = std::make_shared<bcostars::protocol::TransactionReceiptImpl>();
        auto& inner = receipt->inner();
        inner.data.status = 0;
        inner.data.gasUsed = "21000";
        inner.cumulativeGasUsed = "abc";
        inner.logsBloom.assign(256, static_cast<char>(0xab));
        protocol::EthReceiptData eth;
        BOOST_REQUIRE(protocol::toEthReceiptData(*receipt, 1, eth) != nullptr);
    }
    // 0x-prefixed hex form (opstack producer) parses to the same value.
    {
        auto receipt = std::make_shared<bcostars::protocol::TransactionReceiptImpl>();
        auto& inner = receipt->inner();
        inner.data.status = 0;
        inner.data.gasUsed = "21000";
        inner.cumulativeGasUsed = "0x5208";  // 21000 in hex
        inner.logsBloom.assign(256, static_cast<char>(0xab));
        protocol::EthReceiptData eth;
        BOOST_REQUIRE(!protocol::toEthReceiptData(*receipt, 1, eth));
        BOOST_CHECK_EQUAL(eth.cumulativeGasUsed, u256(21000));
    }
    // Bare "0x" with no digits must fail closed (fromHex("") would yield 0).
    {
        auto receipt = std::make_shared<bcostars::protocol::TransactionReceiptImpl>();
        auto& inner = receipt->inner();
        inner.data.status = 0;
        inner.data.gasUsed = "21000";
        inner.cumulativeGasUsed = "0x";
        inner.logsBloom.assign(256, static_cast<char>(0xab));
        protocol::EthReceiptData eth;
        BOOST_REQUIRE(protocol::toEthReceiptData(*receipt, 1, eth) != nullptr);
    }
    // Leading-zero decimal must not be interpreted as octal: "021000" == 21000.
    {
        auto receipt = std::make_shared<bcostars::protocol::TransactionReceiptImpl>();
        auto& inner = receipt->inner();
        inner.data.status = 0;
        inner.data.gasUsed = "21000";
        inner.cumulativeGasUsed = "021000";
        inner.logsBloom.assign(256, static_cast<char>(0xab));
        protocol::EthReceiptData eth;
        BOOST_REQUIRE(!protocol::toEthReceiptData(*receipt, 1, eth));
        BOOST_CHECK_EQUAL(eth.cumulativeGasUsed, u256(21000));
    }
    // Over-256-bit values must fail closed (would wrap modulo 2^256 under boost's
    // unchecked policy).
    {
        auto receipt = std::make_shared<bcostars::protocol::TransactionReceiptImpl>();
        auto& inner = receipt->inner();
        inner.data.status = 0;
        inner.data.gasUsed = "21000";
        inner.cumulativeGasUsed = std::string(65, 'f');  // 65 hex digits > 256 bits
        inner.logsBloom.assign(256, static_cast<char>(0xab));
        protocol::EthReceiptData eth;
        BOOST_REQUIRE(protocol::toEthReceiptData(*receipt, 1, eth) != nullptr);
    }
    {
        auto receipt = std::make_shared<bcostars::protocol::TransactionReceiptImpl>();
        auto& inner = receipt->inner();
        inner.data.status = 0;
        inner.data.gasUsed = "21000";
        inner.cumulativeGasUsed = std::string(79, '9');  // 79 decimal digits > 256 bits
        inner.logsBloom.assign(256, static_cast<char>(0xab));
        protocol::EthReceiptData eth;
        BOOST_REQUIRE(protocol::toEthReceiptData(*receipt, 1, eth) != nullptr);
    }
    // A 78-digit decimal above 2^256-1 must fail closed (unchecked u256 would
    // truncate silently — the 78-digit length bound alone is not tight).
    {
        auto receipt = std::make_shared<bcostars::protocol::TransactionReceiptImpl>();
        auto& inner = receipt->inner();
        inner.data.status = 0;
        inner.data.gasUsed = "21000";
        inner.cumulativeGasUsed = "2" + std::string(77, '0');  // 78 digits > 2^256-1
        inner.logsBloom.assign(256, static_cast<char>(0xab));
        protocol::EthReceiptData eth;
        BOOST_REQUIRE(protocol::toEthReceiptData(*receipt, 1, eth) != nullptr);
    }
}

BOOST_AUTO_TEST_SUITE_END()
}  // namespace bcos::test
