codecov:
  branch: dev
coverage:
  range: 30...100
  notify:
    # require_ci_to_pass: no
    gitter:
      default:
        threshold: 0
        url: https://gitter.im/fisco-bcos/Lobby
  status:
    project:
      app:
        target: 65
        threshold: 0.5
        paths: "!test/"
      default:
        target: 75
        threshold: 0.5
    patch:
      default:
        target: 10
        enabled: no
    changes:
      default:
        enabled: no
comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
flags:
  alltests:
    joined: false
ignore:
  - "**/fisco-bcos/**/*"
  - "**/evmc/**/*"
  - "**/utils/**/*"
  - "**/deps/**/*"
  - "/usr/**/*"
