codecov:
  branch: dev
coverage:
  range: 30...100
  notify:
    gitter:
      default:
        threshold: 0
        url: https://gitter.im/fisco-bcos/Lobby
  status:
    project:
      app:
        target: 80
        threshold: 0.05
        paths: "!test/"
      default:
        target: auto
        threshold: 0.05
    patch:
      default:
        target: 10
    changes:
      default:
        enabled: no
comment:
  layout: "reach, diff"
flags:
  alltests:
    joined: false

