#!/usr/bin/env bash
# Regenerate bcos-evm/test/opstack/op_revm_oracle.json from the pinned op-revm checkout.
# The oracle exists so the Karst precompile table is judged by an EXTERNAL implementation,
# not by its own literals (OpPrecompilesTest used to compare constants to themselves).
set -euo pipefail

OP_REVM_REPO="${OP_REVM_REPO:-}"
[ -n "$OP_REVM_REPO" ] || { echo "OP_REVM_REPO is required (path to the pinned optimism checkout; no machine default)" >&2; exit 1; }
OP_REVM_SUBDIR="${OP_REVM_SUBDIR:-rust/op-revm}"
OUT="${1:-$(cd "$(dirname "$0")/../.." && pwd -P)/bcos-evm/test/opstack/op_revm_oracle.json}"

PRE="$OP_REVM_REPO/$OP_REVM_SUBDIR/src/precompiles.rs"
SPEC="$OP_REVM_REPO/$OP_REVM_SUBDIR/src/spec.rs"
CONST="$OP_REVM_REPO/$OP_REVM_SUBDIR/src/constants.rs"
[ -f "$PRE" ] || { echo "missing $PRE" >&2; exit 1; }
[ -f "$SPEC" ] || { echo "missing $SPEC" >&2; exit 1; }
[ -f "$CONST" ] || { echo "missing $CONST" >&2; exit 1; }

grab() { # grab <const-name> <file>
  grep -oE "$1: usize = [0-9_]+" "$2" | head -1 | grep -oE '[0-9_]+$' | tr -d '_'
}

grab_u64() { # same shape, for the u64 constants in constants.rs
  grep -oE "$1: u64 = [0-9_]+" "$2" | head -1 | grep -oE '[0-9_]+$' | tr -d '_'
}

KARST_BN254="$(grab KARST_MAX_INPUT_SIZE "$PRE")"
JOV_G1="$(grab JOVIAN_G1_MSM_MAX_INPUT_SIZE "$PRE")"
JOV_G2="$(grab JOVIAN_G2_MSM_MAX_INPUT_SIZE "$PRE")"
JOV_PAIR="$(grab JOVIAN_PAIRING_MAX_INPUT_SIZE "$PRE")"
KARST_ETH_SPEC="$(grep -oE 'Self::KARST \| Self::INTEROP => SpecId::[A-Z]+' "$SPEC" | grep -oE '[A-Z]+$')"
# Holocene / Jovian per-value anchors (WI-E5/E6): the ETH spec each fork runs with, plus the
# two numbers the operator-fee formula is built from (Isthmus'/1e6 decimal, Jovian's x100).
HOLOCENE_ETH_SPEC="$(grep -oE 'Self::ECOTONE \| Self::FJORD \| Self::GRANITE \| Self::HOLOCENE => SpecId::[A-Z]+' "$SPEC" | grep -oE '[A-Z]+$')"
JOVIAN_ETH_SPEC="$(grep -oE 'Self::ISTHMUS \| Self::JOVIAN => SpecId::[A-Z]+' "$SPEC" | grep -oE '[A-Z]+$')"
OPERATOR_FEE_DECIMAL="$(grab_u64 OPERATOR_FEE_SCALAR_DECIMAL "$CONST")"
OPERATOR_FEE_JOVIAN_MULT="$(grab_u64 OPERATOR_FEE_JOVIAN_MULTIPLIER "$CONST")"
# P256Verify gas for Karst: Karst activates Osaka, so the OSAKA constant is the one the
# spec runs with (revm-precompile/src/secp256r1.rs defines P256VERIFY_BASE_GAS_FEE=3450 and
# P256VERIFY_BASE_GAS_FEE_OSAKA=6900; grabbing "the number next to P256VERIFY" instead
# matched P256VERIFY_ADDRESS=256, which is the precompile ADDRESS, not a gas).
LOCK="$OP_REVM_REPO/rust/Cargo.lock"
REVM_PRECOMPILE_VER="$(grep -A1 '^name = "revm-precompile"' "$LOCK" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)"
P256_SRC="$(ls -d "${CARGO_HOME:-$HOME/.cargo}"/registry/src/*/revm-precompile-"$REVM_PRECOMPILE_VER"/src 2>/dev/null | head -1)"
P256_GAS=""
if [ -n "$P256_SRC" ]; then
  P256_GAS="$(grep -hoE 'P256VERIFY_BASE_GAS_FEE_OSAKA: u64 = [0-9_]+' \
    "$P256_SRC/secp256r1.rs" | head -1 | grep -oE '[0-9_]+$' | tr -d '_')"
fi

cat > "$OUT" <<EOF
{
  "_comment": "Generated by tools/op-revm-oracle/extract.sh. The Karst precompile table in bcos-evm/bcos-evm/opstack/OpPrecompiles.cpp is judged against THESE values (external implementation), not against its own literals.",
  "source": {
    "crate": "op-revm",
    "repo_hint": "override with the OP_REVM_REPO env var when regenerating; the revision above is the authoritative pin",
    "subdir": "$OP_REVM_SUBDIR",
    "revision": "$(git -C "$OP_REVM_REPO" rev-parse HEAD)",
    "precompiles_rs": "$OP_REVM_SUBDIR/src/precompiles.rs",
    "spec_rs": "$OP_REVM_SUBDIR/src/spec.rs",
    "constants_rs": "$OP_REVM_SUBDIR/src/constants.rs"
  },
  "karst_eth_spec": "$KARST_ETH_SPEC",
  "holocene_eth_spec": "$HOLOCENE_ETH_SPEC",
  "jovian_eth_spec": "$JOVIAN_ETH_SPEC",
  "operator_fee_scalar_decimal": ${OPERATOR_FEE_DECIMAL:-0},
  "operator_fee_jovian_multiplier": ${OPERATOR_FEE_JOVIAN_MULT:-0},
  "bn254_pairing_max_input_size": $KARST_BN254,
  "bls_g1_msm_max_input_size": $JOV_G1,
  "bls_g2_msm_max_input_size": $JOV_G2,
  "bls_pairing_max_input_size": $JOV_PAIR,
  "p256verify_gas": ${P256_GAS:-0},
  "revm_precompile_version": "$REVM_PRECOMPILE_VER"
}
EOF

echo "wrote $OUT"
cat "$OUT"
