set(ITTAPI_INCLUDE_DIR "${CMAKE_CURRENT_LIST_DIR}/../../include")
set(ITTAPI_LIBRARY "${CMAKE_CURRENT_LIST_DIR}/../../lib/${CMAKE_STATIC_LIBRARY_PREFIX}ittnotify${CMAKE_STATIC_LIBRARY_SUFFIX}")

add_library(ittapi STATIC IMPORTED GLOBAL)
set_target_properties(ittapi PROPERTIES
    IMPORTED_LOCATION "${ITTAPI_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${ITTAPI_INCLUDE_DIR}"
)
