/*
 *  Copyright (C) 2026 FISCO BCOS.
 *  SPDX-License-Identifier: Apache-2.0
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 * @file test_NodeConfigEthGenesisHeader.cpp
 * @brief [eth_genesis_header] parsing: 22-field mapping + per-field fail-fast (A3)
 */
#include <bcos-crypto/signature/key/KeyFactoryImpl.h>
#include <bcos-framework/ledger/GenesisConfig.h>
#include <bcos-tool/Exceptions.h>
#include <bcos-tool/NodeConfig.h>
#include <boost/algorithm/string/replace.hpp>
#include <boost/property_tree/ini_parser.hpp>
#include <boost/test/unit_test.hpp>
#include <memory>
#include <set>
#include <sstream>
#include <string>
#include <vector>

using namespace bcos::tool;

namespace
{
boost::property_tree::ptree parseEthIni(std::string const& content)
{
    boost::property_tree::ptree pt;
    std::stringstream ss(content);
    boost::property_tree::read_ini(ss, pt);
    return pt;
}

std::shared_ptr<NodeConfig> makeEthNodeConfig()
{
    return std::make_shared<NodeConfig>(std::make_shared<bcos::crypto::KeyFactoryImpl>());
}

constexpr auto kEthBase =
    "[chain]\nsm_crypto=0\nchain_id=1\ngroup_id=g\n"
    "[consensus]\nconsensus_type=pbft\nblock_tx_count_limit=1000\nleader_period=1\n"
    "node.0=0102030405060708090a0b0c0d0e0f1011121314:1\n"
    "[version]\ncompatibility_version=3.10.0\n"
    "[tx]\ngas_limit=300000000\n"
    "[executor]\nis_auth_check=1\nauth_admin_account=0x0\n";

constexpr auto kEthFeatureL2 = "[features]\nfeature_l2_ethereum_compat=1\n";

constexpr auto kEthAlloc0 =
    "[alloc.0]\naddress=0x43000000000000000000000000000000000000C0\n"
    "balance=0\nnonce=0\ncode=0x6080604052\n";

constexpr std::string_view kEthEmptyTrieRoot =
    "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421";

// Fixture values match tools/opstack-genesis/gen_eth_header_fixture.py
// (DEFAULT_FIELDS); the expected hash below was computed by that script.
const std::vector<std::pair<std::string, std::string>> kEthHeaderFields = {
    {"parent_hash", "0x0000000000000000000000000000000000000000000000000000000000000000"},
    {"sha3_uncles", "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347"},
    {"miner", "0x4200000000000000000000000000000000000011"},
    {"state_root", std::string(kEthEmptyTrieRoot)},
    {"transactions_root", std::string(kEthEmptyTrieRoot)},
    {"receipts_root", std::string(kEthEmptyTrieRoot)},
    {"logs_bloom", "0x" + std::string(512, '0')},
    {"difficulty", "0x0"},
    {"number", "0x0"},
    {"gas_limit", "0x1c9c380"},
    {"gas_used", "0x0"},
    {"timestamp", "0x689d5c00"},
    {"extra_data", "0x00000000fa000000060000000000000000"},
    {"mix_hash", "0x0000000000000000000000000000000000000000000000000000000000000000"},
    {"nonce", "0x0000000000000000"},
    {"base_fee_per_gas", "0x3b9aca00"},
    {"withdrawals_root", std::string(kEthEmptyTrieRoot)},
    {"blob_gas_used", "0x0"},
    {"excess_blob_gas", "0x0"},
    {"parent_beacon_block_root",
        "0x0000000000000000000000000000000000000000000000000000000000000000"},
    {"requests_hash", "0xe3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"},
    // keccak256(rlp(header)) over the 21 fields above; generated by
    // gen_eth_header_fixture.py (independent python rlp + keccak).
    {"hash", "0xb153f41d2651441ace825becbfe2f2b6bf89092864a0ae04b7e0d40a5cf64cc1"},
};

std::string ethHeaderSection(std::string const& skipKey = {})
{
    std::string section = "[eth_genesis_header]\n";
    for (auto const& [key, value] : kEthHeaderFields)
    {
        if (key == skipKey)
        {
            continue;
        }
        section += key + "=" + value + "\n";
    }
    return section;
}

std::string l2EthConfig(std::string const& ethSection)
{
    return std::string(kEthBase) + kEthFeatureL2 + kEthAlloc0 + ethSection;
}
}  // namespace

BOOST_AUTO_TEST_SUITE(NodeConfigEthGenesisHeaderTest)

BOOST_AUTO_TEST_CASE(AllFieldsParsed)
{
    auto cfg = makeEthNodeConfig();
    cfg->loadGenesisConfig(parseEthIni(l2EthConfig(ethHeaderSection())));
    auto const& header = cfg->genesisConfig().m_ethGenesisHeader;
    BOOST_REQUIRE(header.has_value());

    BOOST_CHECK_EQUAL(header->m_parentHash.hex(), std::string(64, '0'));
    BOOST_CHECK_EQUAL(header->m_sha3Uncles.hexPrefixed(),
        "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347");
    BOOST_CHECK_EQUAL(header->m_miner.hexPrefixed(), "0x4200000000000000000000000000000000000011");
    BOOST_CHECK_EQUAL(header->m_stateRoot.hexPrefixed(), std::string(kEthEmptyTrieRoot));
    BOOST_CHECK_EQUAL(header->m_transactionsRoot.hexPrefixed(), std::string(kEthEmptyTrieRoot));
    BOOST_CHECK_EQUAL(header->m_receiptsRoot.hexPrefixed(), std::string(kEthEmptyTrieRoot));
    BOOST_CHECK_EQUAL(header->m_logsBloom.size(), 256U);
    BOOST_CHECK_EQUAL(header->m_difficulty, bcos::u256(0));
    BOOST_CHECK_EQUAL(header->m_number, 0);
    BOOST_CHECK_EQUAL(header->m_gasLimit, bcos::u256(30'000'000));
    BOOST_CHECK_EQUAL(header->m_gasUsed, bcos::u256(0));
    BOOST_CHECK_EQUAL(header->m_timestamp, 0x689d5c00);
    BOOST_CHECK_EQUAL(header->m_extraData.size(), 17U);  // Jovian format
    BOOST_CHECK_EQUAL(header->m_mixHash, bcos::h256{});
    BOOST_CHECK_EQUAL(header->m_nonce, bcos::h64{});
    BOOST_REQUIRE(header->m_baseFeePerGas.has_value());
    BOOST_CHECK_EQUAL(*header->m_baseFeePerGas, bcos::u256(1'000'000'000));
    BOOST_REQUIRE(header->m_withdrawalsRoot.has_value());
    BOOST_CHECK_EQUAL(header->m_withdrawalsRoot->hexPrefixed(), std::string(kEthEmptyTrieRoot));
    BOOST_REQUIRE(header->m_blobGasUsed.has_value());
    BOOST_CHECK_EQUAL(*header->m_blobGasUsed, bcos::u256(0));
    BOOST_REQUIRE(header->m_excessBlobGas.has_value());
    BOOST_CHECK_EQUAL(*header->m_excessBlobGas, bcos::u256(0));
    BOOST_REQUIRE(header->m_parentBeaconBlockRoot.has_value());
    BOOST_CHECK_EQUAL(*header->m_parentBeaconBlockRoot, bcos::h256{});
    BOOST_REQUIRE(header->m_requestsHash.has_value());
    BOOST_CHECK_EQUAL(header->m_requestsHash->hexPrefixed(),
        "0xe3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855");
    BOOST_CHECK_EQUAL(header->m_hash.hexPrefixed(),
        "0xb153f41d2651441ace825becbfe2f2b6bf89092864a0ae04b7e0d40a5cf64cc1");
}

BOOST_AUTO_TEST_CASE(EachMissingRequiredFieldFailsFast)
{
    // Remove every REQUIRED key in turn: parsing must throw InvalidConfig each
    // time. The fork-gated keys (base_fee_per_gas, withdrawals_root,
    // blob_gas_used, excess_blob_gas, parent_beacon_block_root, requests_hash)
    // are OPTIONAL — removing one of those must instead succeed (covered by
    // OptionalFieldsMayBeOmitted below).
    const std::set<std::string> kOptionalKeys = {
        "base_fee_per_gas", "withdrawals_root", "blob_gas_used",
        "excess_blob_gas", "parent_beacon_block_root", "requests_hash",
    };
    for (auto const& [key, value] : kEthHeaderFields)
    {
        if (kOptionalKeys.count(key) > 0)
        {
            continue;
        }
        auto cfg = makeEthNodeConfig();
        BOOST_CHECK_THROW(cfg->loadGenesisConfig(parseEthIni(l2EthConfig(ethHeaderSection(key)))),
            bcos::tool::InvalidConfig);
    }
}

BOOST_AUTO_TEST_CASE(OptionalFieldsMayBeOmitted)
{
    // A pre-Cancun chain (e.g. Sepolia's London-era genesis) omits the
    // fork-gated keys. Each omission must parse cleanly and surface as a
    // nullopt optional, so the ledger's RLP re-encoding leaves the field out.
    const std::set<std::string> kOptionalKeys = {
        "base_fee_per_gas", "withdrawals_root", "blob_gas_used",
        "excess_blob_gas", "parent_beacon_block_root", "requests_hash",
    };
    for (auto const& [key, value] : kEthHeaderFields)
    {
        if (kOptionalKeys.count(key) == 0)
        {
            continue;
        }
        auto cfg = makeEthNodeConfig();
        cfg->loadGenesisConfig(parseEthIni(l2EthConfig(ethHeaderSection(key))));
        auto const& header = cfg->genesisConfig().m_ethGenesisHeader;
        BOOST_REQUIRE(header.has_value());
        if (key == "base_fee_per_gas")
        {
            BOOST_CHECK(!header->m_baseFeePerGas.has_value());
        }
        else if (key == "withdrawals_root")
        {
            BOOST_CHECK(!header->m_withdrawalsRoot.has_value());
        }
        else if (key == "blob_gas_used")
        {
            BOOST_CHECK(!header->m_blobGasUsed.has_value());
        }
        else if (key == "excess_blob_gas")
        {
            BOOST_CHECK(!header->m_excessBlobGas.has_value());
        }
        else if (key == "parent_beacon_block_root")
        {
            BOOST_CHECK(!header->m_parentBeaconBlockRoot.has_value());
        }
        else if (key == "requests_hash")
        {
            BOOST_CHECK(!header->m_requestsHash.has_value());
        }
    }
}

BOOST_AUTO_TEST_CASE(L2WithoutSectionRejected)
{
    // The section and the L2 feature are bound both ways: an L2 chain
    // without [eth_genesis_header] would mint a Tars-hashed B0 no
    // op-node/op-reth could match, so it fails fast.
    auto cfg = makeEthNodeConfig();
    BOOST_CHECK_THROW(
        cfg->loadGenesisConfig(parseEthIni(std::string(kEthBase) + kEthFeatureL2 + kEthAlloc0)),
        bcos::tool::InvalidConfig);
}

BOOST_AUTO_TEST_CASE(SectionWithoutL2FeatureRejected)
{
    auto cfg = makeEthNodeConfig();
    BOOST_CHECK_THROW(
        cfg->loadGenesisConfig(parseEthIni(std::string(kEthBase) + ethHeaderSection())),
        bcos::tool::InvalidConfig);
}

BOOST_AUTO_TEST_CASE(NonZeroNumberRejected)
{
    auto section = ethHeaderSection();
    boost::replace_first(section, "number=0x0\n", "number=0x1\n");
    auto cfg = makeEthNodeConfig();
    BOOST_CHECK_THROW(cfg->loadGenesisConfig(parseEthIni(l2EthConfig(section))),  //
        bcos::tool::InvalidConfig);
}

BOOST_AUTO_TEST_CASE(BadWidthRejected)
{
    // 31-byte state_root
    auto section = ethHeaderSection();
    boost::replace_first(section, std::string(kEthEmptyTrieRoot),
        "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b4");
    auto cfg = makeEthNodeConfig();
    BOOST_CHECK_THROW(cfg->loadGenesisConfig(parseEthIni(l2EthConfig(section))),  //
        bcos::tool::InvalidConfig);

    // 7-byte nonce
    auto shortNonce = ethHeaderSection();
    boost::replace_first(shortNonce, "nonce=0x0000000000000000\n", "nonce=0x00000000000000\n");
    auto cfg2 = makeEthNodeConfig();
    BOOST_CHECK_THROW(cfg2->loadGenesisConfig(parseEthIni(l2EthConfig(shortNonce))),  //
        bcos::tool::InvalidConfig);
}

BOOST_AUTO_TEST_CASE(GenesisDataCoversEthHeader)
{
    // The eth header is part of the genesis pin: two configs that differ only
    // in one header field must produce different genesisData strings, and a
    // config without the section must not mention it at all.
    auto cfg = makeEthNodeConfig();
    cfg->loadGenesisConfig(parseEthIni(l2EthConfig(ethHeaderSection())));
    bcos::ledger::LedgerConfig emptyLedgerConfig;
    auto withHeader = generateGenesisData(cfg->genesisConfig(), emptyLedgerConfig);
    BOOST_CHECK(withHeader.find("[ethGenesisHeader]") != std::string::npos);
    BOOST_CHECK(withHeader.find("0xb153f41d2651441ace825becbfe2f2b6bf89092864a0ae04b7e0d40a5cf64"
                                "cc1") != std::string::npos);

    auto tampered = ethHeaderSection();
    boost::replace_first(tampered, "gas_limit=0x1c9c380\n", "gas_limit=0x1c9c381\n");
    auto cfg2 = makeEthNodeConfig();
    cfg2->loadGenesisConfig(parseEthIni(l2EthConfig(tampered)));
    BOOST_CHECK(withHeader != generateGenesisData(cfg2->genesisConfig(), emptyLedgerConfig));

    // A non-L2 chain (no feature, no allocs, no section) must not mention
    // the section in its genesis pin at all.
    auto cfg3 = makeEthNodeConfig();
    cfg3->loadGenesisConfig(parseEthIni(std::string(kEthBase)));
    auto withoutHeader = generateGenesisData(cfg3->genesisConfig(), emptyLedgerConfig);
    BOOST_CHECK(withoutHeader.find("[ethGenesisHeader]") == std::string::npos);
}

BOOST_AUTO_TEST_SUITE_END()
