{
 "title": "Fisco Bcos Monitoring for 3.0.0",
 "description": "A beta version of the HLF 1.4 Monitoring Dashboard.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Fisco Bcos Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "区块高度",
   "type": "stat",
   "description": "Height of the chain in blocks. ",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ledger_block_height{node=\"node0\"}"
    }
   ]
  },
  {
   "title": "p2p当前活跃会话数",
   "type": "stat",
   "description": "p2p当前活跃会话数",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "p2p_session_actived{node=\"node0\"}"
    }
   ]
  },
  {
   "title": "待打包的交易数量",
   "type": "stat",
   "description": "Number of transactions processed.",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "txpool_pending_tx_size{node=\"node0\"}"
    }
   ]
  },
  {
   "title": "区块高度",
   "type": "graph",
   "description": "Height of the chain in blocks. ",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ledger_block_height{}" }
   ]
  },
  {
   "title": "p2p当前活跃会话数",
   "type": "graph",
   "description": "The number of proposals received.",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "p2p_session_actived{}" }
   ]
  },
  {
   "title": "待打包的交易数量",
   "type": "graph",
   "description": "Number of transactions processed.",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "txpool_pending_tx_size{}" }
   ]
  },
  {
   "title": "节点区块执行时间",
   "type": "graph",
   "description": "Number of transactions processed.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "block_exec_duration_milliseconds_gauge{}"
    }
   ]
  },
  {
   "title": "节点区块提交时间",
   "type": "graph",
   "description": "Height of the chain in blocks. ",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "block_commit_duration_milliseconds_gauge"
    }
   ]
  },
  {
   "title": "节点区块执行时间",
   "type": "graph",
   "description": "ledger_block_exec_duration_bucket",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "个数" }
   ],
   "targets": [
    {
     "expr": "block_exec_duration_milliseconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "节点区块提交时间",
   "type": "graph",
   "description": "ledger_block_commit_duration_bucket",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "个数" }
   ],
   "targets": [
    {
     "expr": "block_commit_duration_milliseconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}