/**
 *  Copyright (C) 2026 FISCO BCOS.
 *  SPDX-License-Identifier: Apache-2.0
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 * @file OpEngineApiMatrixTest.cpp
 * @brief M1: fork x Engine-method window matrix against the pinned op-node artifact.
 */

// M1: every (fork, method) window must equal the pinned op-node's selection, except
// for cells recorded in matrix/known_deviations.json. The artifact is generated by
// the corpus regen ritual (op-stack-e2e-tests); its absence skips rather than fails.
#include <algorithm>
#include <fstream>
#include <optional>
#include <set>
#include <string>
#include <vector>

#include "bcos-framework/engine/OpForkId.h"
#include "bcos-framework/engine/Types.h"         // ApiVersion V1=1..V5=5
#include <bcos-evm/opstack/OpForkSchedule.h>     // parse()/forkAt(): name -> OpFork
#include <engine/bcos-engine/OpEngineService.h>  // engine_common::op::supportedOpCapabilities
#include <opstack-executor/OpSchedulerSeam.h>    // bcos::evm::engine::detail::tryEngineForkId

#include <fmt/format.h>
#include <json/json.h>
#include <boost/test/tree/decorator.hpp>
#include <boost/test/unit_test.hpp>

namespace
{
constexpr std::string_view c_matrixDir = OP_MATRIX_DIR;

std::optional<Json::Value> loadJson(std::string const& name)
{
    std::ifstream in(std::string(c_matrixDir) + "/" + name);
    if (!in)
    {
        return std::nullopt;
    }
    Json::Value root;
    Json::CharReaderBuilder builder;
    std::string errors;
    if (!Json::parseFromStream(builder, in, &root, &errors))
    {
        BOOST_FAIL("cannot parse " + name + ": " + errors);
    }
    return root;
}

/// The artifact carries op-node's eth.EngineAPIMethod values, which ARE the full engine
/// method names (e.g. "engine_newPayloadV2"); this lane's profile holds ApiVersion V1=1..V5=5,
/// so the comparison renders the same naming rule op-geth uses (engine_ + family + version).
std::string methodName(bcos::engine::OpForkId fork, std::string_view method)
{
    auto const profile = bcos::engine::engineApiProfileFor(fork);
    std::uint32_t version = 0;
    if (method == "newPayload")
    {
        version = static_cast<std::uint32_t>(profile.newPayload);
    }
    else if (method == "forkchoiceUpdated")
    {
        version = static_cast<std::uint32_t>(profile.forkchoiceUpdated);
    }
    else
    {
        version = static_cast<std::uint32_t>(profile.getPayload);
    }
    return "engine_" + std::string(method) + "V" + std::to_string(version);
}

bool isRecordedDeviation(Json::Value const& deviations, std::string const& fork,
    std::string const& method, std::string const& expected, std::string const& implemented)
{
    for (auto const& d : deviations)  // caller passes (*deviations)["deviations"]
    {
        if (d["fork"].asString() == fork && d["method"].asString() == method &&
            d["expected_from_pin"].asString() == expected &&
            d["implemented"].asString() == implemented)
        {
            return true;
        }
    }
    return false;
}
}  // namespace

BOOST_AUTO_TEST_SUITE(OpEngineApiMatrixSuite)

/// Positive cells: for every fork the pinned op-node selects, this lane's profile must
/// select the same method -- unless the cell is an explicitly recorded deviation
/// (currently only karst/getPayload, where the pinned op-node has no KarstTime at all).
// clang-format off
BOOST_AUTO_TEST_CASE(ForkMethodWindowsMatchPinnedOpNode, * boost::unit_test::label("fork-regolith") * boost::unit_test::label("fork-canyon") * boost::unit_test::label("fork-ecotone") * boost::unit_test::label("fork-fjord") * boost::unit_test::label("fork-granite") * boost::unit_test::label("fork-holocene") * boost::unit_test::label("fork-isthmus") * boost::unit_test::label("fork-jovian") * boost::unit_test::label("fork-karst"))
// clang-format on
{
    auto windows = loadJson("engine_api_windows.json");
    auto deviations = loadJson("known_deviations.json");
    auto caps = loadJson("caps.json");
    if (!windows || !deviations || !caps)
    {
        BOOST_TEST_MESSAGE("matrix artifacts absent; run the corpus regen ritual -- skipping");
        return;
    }
    std::size_t checked = 0;
    for (auto const& row : (*windows)["windows"])
    {
        auto const fork = row["fork"].asString();
        // name -> OpFork via the public schedule parser, then OpFork -> OpForkId via the
        // seam's mapping (there is no name->OpForkId helper; the engine enum is renumbered).
        auto const id = bcos::evm::engine::detail::tryEngineForkId(
            bcos::evm::opstack::OpForkSchedule::parse("0:" + fork).forkAt(0));
        BOOST_REQUIRE_MESSAGE(
            id.has_value(), "artifact carries a fork the engine does not model: " + fork);
        for (auto const method : {"newPayload", "forkchoiceUpdated", "getPayload"})
        {
            auto const expected = row[method].asString();
            auto const implemented = methodName(*id, method);
            if (expected == implemented)
            {
                ++checked;
                continue;
            }
            // NOTE the argument order: the helper signature is
            // (deviations, fork, method, expected, implemented).
            BOOST_CHECK_MESSAGE(isRecordedDeviation((*deviations)["deviations"], fork, method,
                                    expected, implemented),
                fmt::format("unrecorded window divergence {}/{}: pin={} vs implemented={}", fork,
                    method, expected, implemented));
        }
    }
    // Derive the cell count from the artifact rather than hardcoding it: the matrix is a
    // tracked contract in op-stack-e2e-tests, and bumping that pin changes the row set
    // (e.g. a Karst-aware op-node adds a karst row). A literal would go stale silently.
    // Two invariants: (a) every cell is either equal or a recorded deviation, so
    // checked == total - deviated; (b) the deviated count equals the recorded entries,
    // so a stale entry in known_deviations.json fails here instead of lingering.
    std::size_t totalCells = 0;
    std::size_t deviatedCells = 0;
    for (auto const& row : (*windows)["windows"])
    {
        auto const fork = row["fork"].asString();
        auto const id = bcos::evm::engine::detail::tryEngineForkId(
            bcos::evm::opstack::OpForkSchedule::parse("0:" + fork).forkAt(0));
        BOOST_REQUIRE_MESSAGE(
            id.has_value(), "artifact carries a fork the engine does not model: " + fork);
        for (auto const method : {"newPayload", "forkchoiceUpdated", "getPayload"})
        {
            ++totalCells;
            if (row[method].asString() != methodName(*id, method))
            {
                ++deviatedCells;
            }
        }
    }
    BOOST_CHECK_GT(totalCells, 0U);
    BOOST_TEST_MESSAGE("matrix cells: total=" << totalCells << " deviated=" << deviatedCells
                                              << " checked=" << checked);
    BOOST_CHECK_EQUAL(checked, totalCells - deviatedCells);
    BOOST_CHECK_EQUAL(deviatedCells, (*deviations)["deviations"].size());
    // The advertised caps must cover the union of the windows (same naming rule as
    // op-geth, whose list is the caps.json artifact); anything advertised outside the
    // three families must at least exist in op-geth's list.
    auto const advertised = bcos::engine::engine_common::op::supportedOpCapabilities();
    std::set<std::string> advertisedSet(advertised.begin(), advertised.end());
    std::set<std::string> opGethCaps;
    for (auto const& c : (*caps)["caps"])
    {
        opGethCaps.insert(c.asString());
    }
    std::set<std::string> derived;
    for (auto const& row : (*windows)["windows"])
    {
        derived.insert(row["newPayload"].asString());
        derived.insert(row["forkchoiceUpdated"].asString());
        derived.insert(row["getPayload"].asString());
    }
    for (auto const& cap : derived)
    {
        BOOST_CHECK_MESSAGE(advertisedSet.count(cap) != 0, "window method not advertised: " + cap);
        BOOST_CHECK_MESSAGE(opGethCaps.count(cap) != 0, "method absent upstream: " + cap);
    }
    for (auto const& cap : advertisedSet)
    {
        if (cap.rfind("engine_newPayload", 0) == 0 ||
            cap.rfind("engine_forkchoiceUpdated", 0) == 0 || cap.rfind("engine_getPayload", 0) == 0)
        {
            // A recorded deviation explains an advertised method outside the window
            // union (karst getPayloadV5 is exactly that), so exempt it explicitly.
            bool deviated = false;
            for (auto const& d : (*deviations)["deviations"])
            {
                deviated = deviated || (d["implemented"].asString() == cap);
            }
            BOOST_CHECK_MESSAGE(derived.count(cap) != 0 || deviated,
                "advertised method is outside every fork window: " + cap);
        }
    }
    BOOST_TEST_MESSAGE("matrix cells checked: " << checked);
}

/// M1 negative cells: the pre-Bedrock payload methods must not be advertised at all,
/// FCU V4 (which exists upstream but this lane answers -38005 for) must not be either,
/// and every advertised method must exist in op-geth's reflective list.
///
/// The runtime half of this cell -- actually sending a window-foreign version and
/// observing UnsupportedFork (-38005) -- is already driven elsewhere, so it is not
/// duplicated here: OpEngineApiVersionsTest::NewPayloadWrongVersionIsUnsupportedFork
/// (V4 at Canyon time, V2 at Ecotone time), OpEngineServiceParityTest (getPayload V5 at
/// a Jovian timestamp) and EngineServiceTest.cpp:1889 (out-of-window versions).
// clang-format off
BOOST_AUTO_TEST_CASE(WindowForeignVersionIsRejectedAndV1IsAbsent, * boost::unit_test::label("fork-regolith") * boost::unit_test::label("fork-canyon") * boost::unit_test::label("fork-ecotone") * boost::unit_test::label("fork-fjord") * boost::unit_test::label("fork-granite") * boost::unit_test::label("fork-holocene") * boost::unit_test::label("fork-isthmus") * boost::unit_test::label("fork-jovian") * boost::unit_test::label("fork-karst"))
// clang-format on
{
    auto caps = loadJson("caps.json");
    if (!caps)
    {
        BOOST_TEST_MESSAGE("caps artifact absent; skipping");
        return;
    }
    auto const advertised = bcos::engine::engine_common::op::supportedOpCapabilities();
    // V1: op-node never selects newPayloadV1/getPayloadV1 (Bedrock is its first fork).
    BOOST_CHECK(
        std::find(advertised.begin(), advertised.end(), "engine_newPayloadV1") == advertised.end());
    BOOST_CHECK(
        std::find(advertised.begin(), advertised.end(), "engine_getPayloadV1") == advertised.end());
    // FCU V4 must not be advertised either (upstream has it; this lane answers -38005).
    BOOST_CHECK(std::find(advertised.begin(), advertised.end(), "engine_forkchoiceUpdatedV4") ==
                advertised.end());
    // Every advertised method must exist in op-geth's reflective list (naming-rule guard)
    // -- except engine_exchangeCapabilities: op-geth's own reflection SKIPS the method
    // itself (eth/catalyst/api.go, `if name == "ExchangeCapabilities" { continue }`),
    // while this lane advertises it. Measured: op-geth's list has 36 entries and does not
    // contain engine_exchangeCapabilities.
    Json::Value const& gethCaps = (*caps)["caps"];
    for (auto const& cap : advertised)
    {
        if (cap.rfind("engine_", 0) != 0 || cap == "engine_exchangeCapabilities")
        {
            continue;
        }
        bool present = false;
        for (auto const& c : gethCaps)
        {
            present = present || (c.asString() == cap);
        }
        BOOST_CHECK_MESSAGE(present, "advertised method absent upstream: " + cap);
    }
}

BOOST_AUTO_TEST_SUITE_END()
