#!/usr/bin/env bash
# Copyright (c) FISCO-BCOS, Apache-2.0
#
# enode.sh — print this container's devp2p enode URL (hive eth1 contract).
# The identity key is generated by bcos.sh at container start.
set -u

IP=$(hostname -i 2>/dev/null | awk '{print $1}')
IP=${IP:-127.0.0.1}
exec eth-sync-check --enode-from-key /bcos/node.rlpx.key --ip "${IP}" --port 30303
