include(FindPackageHandleStandardArgs)
include(ExternalProject)
include(GNUInstallDirs)

add_library(EVMONE MODULE IMPORTED)
# Check found directory
if(NOT EVMONE_ROOT_DIR)
  message(STATUS "Install EVMONE from github")
  set(EVMONE_INSTALL ${CMAKE_CURRENT_BINARY_DIR}/evmone-install)

  ExternalProject_Add(evmc-project
    URL https://github.com/FISCO-BCOS/evmone/archive/37799f8226c72e2e64e59583f07ab834868de33e.tar.gz
    URL_HASH SHA1=cd2d588087b0b951c773499a74a6725e538c5c49
    CMAKE_ARGS -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=${EVMONE_INSTALL} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
  )

  set(EVMONE_INCLUDE_DIRS "${EVMONE_INSTALL}/include")
  set(EVMONE_LIBRARIES
    "${EVMONE_INSTALL}/${CMAKE_INSTALL_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}evmc-instructions${CMAKE_STATIC_LIBRARY_SUFFIX}"
    "${EVMONE_INSTALL}/${CMAKE_INSTALL_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}evmc-loader${CMAKE_STATIC_LIBRARY_SUFFIX}"
  )
  
  add_dependencies(EVMONE evmc-project)
  set(EVMONE_ROOT_DIR ${EVMONE_INSTALL})
endif()

message(STATUS "Find EVMONE in ${EVMONE_ROOT_DIR}")
find_path(EVMONE_INCLUDE_DIRS NAMES evmc PATHS ${EVMONE_ROOT_DIR}/include/ REQUIRED)
find_library(EVMONE_LIBRARIES NAMES
  ${CMAKE_STATIC_LIBRARY_PREFIX}evmc-instructions${CMAKE_STATIC_LIBRARY_SUFFIX}
  ${CMAKE_STATIC_LIBRARY_PREFIX}evmc-loader${CMAKE_STATIC_LIBRARY_SUFFIX}
  PATHS ${EVMONE_ROOT_DIR}/${CMAKE_INSTALL_LIBDIR} REQUIRED)

target_include_directories(EVMONE INTERFACE ${EVMONE_INCLUDE_DIRS})
set_property(TARGET EVMONE PROPERTY IMPORTED_LOCATION ${EVMONE_LIBRARIES})

set(EVMONE_FOUND ON)