include(FindPackageHandleStandardArgs)
include(ExternalProject)
include(GNUInstallDirs)

add_library(EVMC MODULE IMPORTED)
# Check found directory
if(NOT EVMC_ROOT_DIR)
  message(STATUS "Install EVMC from github")
  set(EVMC_INSTALL ${CMAKE_CURRENT_BINARY_DIR}/evmc-install)

  ExternalProject_Add(evmc-project
    URL https://${URL_BASE}/FISCO-BCOS/evmc/archive/e0bd9d5dc68ec3a00fe9a3c5e81c98946449a20d.tar.gz
    URL_HASH SHA1=34acad43523f85531fb4b0ab8af60f2e45ff1989
    CMAKE_ARGS -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=${EVMC_INSTALL} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
  )

  set(EVMC_INCLUDE_DIRS "${EVMC_INSTALL}/include")
  make_directory(${EVMC_INCLUDE_DIRS})
  set(EVMC_LIBRARIES
    "${EVMC_INSTALL}/${CMAKE_INSTALL_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}evmc-instructions${CMAKE_STATIC_LIBRARY_SUFFIX}"
    "${EVMC_INSTALL}/${CMAKE_INSTALL_LIBDIR}/${CMAKE_STATIC_LIBRARY_PREFIX}evmc-loader${CMAKE_STATIC_LIBRARY_SUFFIX}"
  )
  
  add_dependencies(EVMC evmc-project)
  set(EVMC_ROOT_DIR ${EVMC_INSTALL})
endif()

message(STATUS "Find EVMC in ${EVMC_ROOT_DIR}")
find_path(EVMC_INCLUDE_DIRS NAMES evmc PATHS ${EVMC_ROOT_DIR}/include/ REQUIRED)
find_library(EVMC_LIBRARIES NAMES
  ${CMAKE_STATIC_LIBRARY_PREFIX}evmc-instructions${CMAKE_STATIC_LIBRARY_SUFFIX}
  ${CMAKE_STATIC_LIBRARY_PREFIX}evmc-loader${CMAKE_STATIC_LIBRARY_SUFFIX}
  PATHS ${EVMC_ROOT_DIR}/${CMAKE_INSTALL_LIBDIR} REQUIRED)

target_include_directories(EVMC INTERFACE ${EVMC_INCLUDE_DIRS})
set_property(TARGET EVMC PROPERTY IMPORTED_LOCATION ${EVMC_LIBRARIES})

set(EVMC_FOUND ON)