include_directories(${CMAKE_CURRENT_SOURCE_DIR})
# include_directories(${CMAKE_CURRENT_BINARY_DIR})
# include_directories(${CMAKE_CURRENT_BINARY_DIR}/bcos-protocol)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/bcos-protocol)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/bcos-utilities)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/bcos-framework)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/bcos-txpool)
if (NOT ONLY_CPP_SDK)
    include_directories(${CMAKE_CURRENT_BINARY_DIR}/bcos-txpool)
endif ()
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/bcos-front)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/bcos-sealer)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/bcos-pbft)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/bcos-rpbft)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/bcos-sync)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/bcos-gateway)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/bcos-rpc)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/bcos-security)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/bcos-tool)
# include_directories(${CMAKE_CURRENT_SOURCE_DIR}/fisco-bcos-tars-service)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/bcos-crypto)