include(ExternalProject)
include(GNUInstallDirs)

set(TASSL_CONFIG_COMMAND bash config -Wl,--rpath=./ shared )
set(TASSL_BUILD_COMMAND make)

ExternalProject_Add(tassl
    PREFIX ${CMAKE_SOURCE_DIR}/deps
    DOWNLOAD_NO_PROGRESS 1
    URL https://github.com/xxxx/TASSL-master.zip
    URL_HASH SHA256=7f3aed16012e4301e8afa88a9972d2fe019ce62b145b61c8c48cfa6c5490ec0a
    BUILD_IN_SOURCE 1
    CONFIGURE_COMMAND ${TASSL_CONFIG_COMMAND}
    LOG_CONFIGURE 1
    BUILD_COMMAND ${TASSL_BUILD_COMMAND}
    INSTALL_COMMAND ""
)

ExternalProject_Get_Property(tassl SOURCE_DIR)
set(TASSL_SUFFIX .a)
set(OPENSSL_INCLUDE_DIRS ${SOURCE_DIR}/include)
set(OPENSSL_SSL_LIBRARIE ${SOURCE_DIR}/libssl${TASSL_SUFFIX})
set(OPENSSL_CRYPTO_LIBRARIE ${SOURCE_DIR}/libcrypto${TASSL_SUFFIX})

#message(STATUS "###OPENSSL_SSL_LIBRARIE:${OPENSSL_SSL_LIBRARIE}")
#message(STATUS "###OPENSSL_CRYPTO_LIBRARIE:${OPENSSL_CRYPTO_LIBRARIE}")
#message(STATUS "##OPENSSL_INCLUDE_DIRS: ${OPENSSL_INCLUDE_DIRS}")
