function(eth_apply TARGET REQUIRED)
	if (BUILD_GM)
		target_include_directories(${TARGET} SYSTEM PUBLIC ${TASSL_INCLUDE_DIRS})
		target_link_libraries(${TARGET} ${TASSL_LIBRARIES})
	else()
		find_package (OpenSSL QUIET)
		set(OPENSSL_INCLUDE_DIRS ${OPENSSL_INCLUDE_DIR})
		eth_show_dependency(OPENSSL OpenSSL)
		if (OPENSSL_FOUND)
			target_include_directories(${TARGET} SYSTEM PUBLIC ${OPENSSL_INCLUDE_DIRS})
			target_link_libraries(${TARGET} ${OPENSSL_LIBRARIES})
		elseif (NOT ${REQUIRED} STREQUAL "OPTIONAL")
			message(FATAL_ERROR "OpenSSL library not found")
		endif()
	endif()
endfunction()