/**
 *  Copyright (C) 2026 FISCO BCOS.
 *  SPDX-License-Identifier: Apache-2.0
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 * @file New1_Web3TxHashCanonicalTest.cpp
 * @brief FIB-New1: verify() recomputes the canonical Web3 txHash from the signing preimage
 *        (extraTransactionBytes) + signature via TransactionImpl::calculateHash(), so a P2P peer
 *        cannot forge the wire-supplied extraTransactionHash.
 *
 * These are KNOWN-ANSWER tests. Each vector is (signing-preimage, signature, canonical-txHash),
 * where the preimage is Web3Transaction::encodeForSign() and the canonical-txHash was produced by
 * the trusted Web3Transaction::txHash() oracle (itself checked against go-ethereum vectors in
 * bcos-rpc/test/Web3TypeTest). Freezing the expected hashes as constants keeps this test at the
 * bcos-tars-protocol layer -- it needs no dependency on bcos-rpc / Web3Transaction -- and stops the
 * expected values from silently drifting with the implementation. All vectors are signed by the
 * private key 0xdead...beef so recoverAddress() succeeds and verify() runs to completion.
 */

#include <bcos-crypto/hash/Keccak256.h>
#include <bcos-crypto/signature/secp256k1/Secp256k1Crypto.h>
#include <bcos-tars-protocol/protocol/TransactionImpl.h>
#include <bcos-tars-protocol/tars/Transaction.h>
#include <bcos-utilities/DataConvertUtility.h>
#include <boost/test/unit_test.hpp>
#include <array>
#include <memory>
#include <string_view>

using namespace bcos;
using namespace bcos::crypto;

namespace bcos::test
{
namespace
{
struct Vector
{
    std::string_view name;
    std::string_view preimageHex;   // extraTransactionBytes = Web3Transaction::encodeForSign()
    std::string_view signatureHex;  // r(32) || s(32) || yParity(1)
    std::string_view canonicalHex;  // expected keccak256(rlp(signed tx))
};

// Generated by the Web3Transaction oracle (nonce=7, gas=21000, maxPriorityFee=1gwei,
// maxFee=2gwei, value=1e15, to=0x727f..169a, data=0xdeadbeef) and independently confirmed
// against the plan-B byte-splice recompute.
// clang-format off
constexpr std::array<Vector, 5> VECTORS{{
    {"legacy_pre_eip155",
        "eb07847735940082520894727fc6a68321b754475c668a6abfb6e9e71c169a87038d7ea4c6800084deadbeef",
        "a31b27f37d25064dede61b1bf9649134318f38f31a0b75376b77d0fb3e6f70d90d505feb95719789060cce3592145b9e"
        "309de267cc878ac85eae5a1fa5462beb00",
        "b2c20c0c72a91024dedbcf57a37e4eb0bbc8e30776902f577f904638e43a71b2"},
    {"legacy_eip155_chain1",
        "ee07847735940082520894727fc6a68321b754475c668a6abfb6e9e71c169a87038d7ea4c6800084deadbeef018080",
        "94f5e0158ba372a7b451996ac591fec2055d7ca7d0f72aa6b473d7b84a69d58262a22960ade9f059d389489fff300213"
        "df3ef0e09e7b4ab89508b934530c566101",
        "c063947c632cfcf52d7a11c9e8887430bcfb673b2bfc33ddc6d961ba77ffa2f4"},
    {"legacy_eip155_chain1337",
        "f007847735940082520894727fc6a68321b754475c668a6abfb6e9e71c169a87038d7ea4c6800084deadbeef82053980"
        "80",
        "beb0472e1fcad9f02fafae6a631e6b0c4be8a0c1f74ed54d9d2654ae02e6149a4f50a93d6ea03a0c1b13e26245882421"
        "8a80d586ba0b10df8113c2918ffa1dc801",
        "15f417e7e9a83754c74742402e46695d7fb3e953caf214d6cdf31a9541a3c2c1"},
    {"eip1559_chain5",
        "02f20507843b9aca00847735940082520894727fc6a68321b754475c668a6abfb6e9e71c169a87038d7ea4c6800084de"
        "adbeefc0",
        "3dc2e61019aa7824a7e290f2b097d10a405e989fe4d3348268df2afcf647b4086e02084295955b070394ea8e604d86b4"
        "942e4a1638358dca984e9f6adff46d4a01",
        "220e457c18458cbed1fe2345901fdce4374c2c088416e3c8decf3859f2183ef2"},
    {"eip2930_chain5",
        "01ed0507847735940082520894727fc6a68321b754475c668a6abfb6e9e71c169a87038d7ea4c6800084deadbeefc0",
        "07f6e9652e1023b331f7f8a129ceae1bd9340d4b308b003de8adf70f77f254d93d4061a37f52a20a6b10b77ea63aacab"
        "3a2d8266d4db8553b2f0b5f727b7abbb00",
        "e63657a2bdb36ae8b668014c3f8d95c4bd1c0ddea57fc0c1a3e5705fb86a0fd5"},
}};
// clang-format on

// Build the tars Transaction that verify() sees, matching what EthEndpoint::sendRawTransaction
// stores: type=Web3, extraTransactionBytes=signing preimage, signature=r||s||yParity. When
// prewriteCanonicalHash is true this simulates the RPC path (locally-trusted hash pre-written);
// otherwise a caller may inject a forged extraTransactionHash to simulate the P2P path.
bcostars::Transaction buildTars(const Vector& v, bool prewriteCanonicalHash)
{
    bcostars::Transaction t{};
    t.type = static_cast<tars::Char>(bcos::protocol::TransactionType::Web3Transaction);
    auto const preimage = fromHex(v.preimageHex);
    t.extraTransactionBytes.assign(preimage.begin(), preimage.end());
    auto const sig = fromHex(v.signatureHex);
    t.signature.assign(sig.begin(), sig.end());
    if (prewriteCanonicalHash)
    {
        auto const hash = fromHex(v.canonicalHex);
        t.extraTransactionHash.assign(hash.begin(), hash.end());
    }
    return t;
}

std::shared_ptr<bcostars::protocol::TransactionImpl> wrap(bcostars::Transaction&& t)
{
    return std::make_shared<bcostars::protocol::TransactionImpl>(
        [inner = std::move(t)]() mutable { return std::addressof(inner); });
}

HashType expectedHash(const Vector& v)
{
    return HashType(fromHex(v.canonicalHex));
}

}  // namespace

struct New1Fixture
{
    Keccak256 hashImpl;
    Secp256k1Crypto signatureImpl;
};

BOOST_FIXTURE_TEST_SUITE(New1Web3TxHashCanonicalTest, New1Fixture)

// N1_T1: RPC clean path -- clearSenderAndHash() (as TxValidator::verify does) clears the
// pre-written hash and verify() recomputes it; hash() returns the same canonical value either way.
BOOST_AUTO_TEST_CASE(N1_T1_rpc_clean_recomputes_canonical)
{
    for (auto const& v : VECTORS)
    {
        auto tx = wrap(buildTars(v, /*prewriteCanonicalHash=*/true));
        BOOST_TEST_CONTEXT(v.name)
        {
            BOOST_CHECK(tx->tainted());
            tx->clearSenderAndHash();  // clears the pre-written hash -> verify() recomputes it
            tx->verify(hashImpl, signatureImpl);
            BOOST_CHECK(!tx->tainted());
            BOOST_CHECK_EQUAL(tx->hash(), expectedHash(v));
            BOOST_CHECK(!tx->sender().empty());
        }
    }
}

// N1_T2: P2P import with a FORGED wire hash. clearSenderAndHash() drops the untrusted value and
// marks the tx tainted, verify() recomputes -- hash() must return the true canonical value, never
// the attacker-supplied one. This is the core FIB-New1 property.
BOOST_AUTO_TEST_CASE(N1_T2_p2p_overwrites_forged_hash)
{
    for (auto const& v : VECTORS)
    {
        auto tars = buildTars(v, /*prewriteCanonicalHash=*/false);
        bcos::bytes forged(32, 0xab);
        tars.extraTransactionHash.assign(forged.begin(), forged.end());
        auto tx = wrap(std::move(tars));
        BOOST_TEST_CONTEXT(v.name)
        {
            tx->clearSenderAndHash();  // drops the untrusted wire hash + marks tainted
            tx->verify(hashImpl, signatureImpl);
            BOOST_CHECK_EQUAL(tx->hash(), expectedHash(v));
            BOOST_CHECK_NE(tx->hash(), HashType(forged.data(), forged.size()));
        }
    }
}

// N1_T3: clearSenderAndHash() drops the wire-supplied extraTransactionHash so verify() is forced to
// recompute it. Guards against a regression that stops clearing it on the re-verification path.
BOOST_AUTO_TEST_CASE(N1_T3_clearSenderAndHash_clears_extra_hash)
{
    auto const& v = VECTORS[0];
    auto tars = buildTars(v, /*prewriteCanonicalHash=*/false);
    bcos::bytes marker(32, 0xcd);
    tars.extraTransactionHash.assign(marker.begin(), marker.end());
    auto tx = wrap(std::move(tars));
    tx->clearSenderAndHash();
    BOOST_CHECK(tx->mutableInner().extraTransactionHash.empty());
}

// N1_T4: tainted=false short-circuits verify(). After a successful verify, poking
// extraTransactionHash and calling verify() again does NOT recompute/overwrite.
BOOST_AUTO_TEST_CASE(N1_T4_tainted_false_skips_recompute)
{
    auto const& v = VECTORS[1];
    auto tx = wrap(buildTars(v, /*prewriteCanonicalHash=*/true));
    tx->verify(hashImpl, signatureImpl);
    BOOST_CHECK(!tx->tainted());
    bcos::bytes poke(32, 0xef);
    tx->mutableInner().extraTransactionHash.assign(poke.begin(), poke.end());
    tx->verify(hashImpl, signatureImpl);  // tainted() == false -> no-op
    BOOST_CHECK_EQUAL(tx->hash(), HashType(poke.data(), poke.size()));
}

// N1_T5: for a Web3 tx, verify() stores the canonical hash in extraTransactionHash (what hash()
// reads) and leaves dataHash empty -- no separate dataHash is kept for Web3.
BOOST_AUTO_TEST_CASE(N1_T5_web3_hash_from_extra_not_datahash)
{
    auto const& v = VECTORS[0];
    auto tx = wrap(buildTars(v, /*prewriteCanonicalHash=*/false));
    tx->clearSenderAndHash();
    tx->verify(hashImpl, signatureImpl);
    BOOST_CHECK_EQUAL(tx->hash(), expectedHash(v));
    BOOST_CHECK(tx->inner().dataHash.empty());
    BOOST_CHECK_EQUAL(tx->inner().extraTransactionHash.size(), 32u);
}

// N1_T6: BCOSTransaction (type=0) is unaffected -- verify() delegates to the base-class path (which
// throws here because the synthesized tx has no usable signature). The Web3 recompute is not run.
BOOST_AUTO_TEST_CASE(N1_T6_bcos_tx_unaffected)
{
    bcostars::Transaction t{};
    t.type = static_cast<tars::Char>(bcos::protocol::TransactionType::BCOSTransaction);
    t.data.nonce = "1";
    t.data.chainID = "testChain";
    t.data.groupID = "testGroup";
    auto tx = wrap(std::move(t));
    BOOST_CHECK_THROW(tx->verify(hashImpl, signatureImpl), std::exception);
}

// N1_T7: forged extraTransactionBytes (a body byte flipped). Recompute is over a different
// preimage, so the canonical hash MUST differ from the true one (or recover fails and verify
// throws).
BOOST_AUTO_TEST_CASE(N1_T7_forged_bytes_changes_hash_or_throws)
{
    for (auto const& v : VECTORS)
    {
        auto tars = buildTars(v, /*prewriteCanonicalHash=*/false);
        BOOST_REQUIRE_GT(tars.extraTransactionBytes.size(), 8u);
        tars.extraTransactionBytes[tars.extraTransactionBytes.size() - 3] ^= 0x01;
        auto tx = wrap(std::move(tars));
        tx->clearSenderAndHash();
        BOOST_TEST_CONTEXT(v.name)
        {
            bool threw = false;
            try
            {
                tx->verify(hashImpl, signatureImpl);
            }
            catch (std::exception const&)
            {
                threw = true;
            }
            if (!threw)
            {
                BOOST_CHECK_NE(tx->hash(), expectedHash(v));
            }
        }
    }
}

// N1_T8: malformed extraTransactionBytes (garbage) -> decode fails, verify throws.
BOOST_AUTO_TEST_CASE(N1_T8_malformed_bytes_throws)
{
    auto tars = buildTars(VECTORS[0], /*prewriteCanonicalHash=*/false);
    tars.extraTransactionBytes.assign({static_cast<char>(0xff), static_cast<char>(0xff),
        static_cast<char>(0xff), static_cast<char>(0xff)});
    auto tx = wrap(std::move(tars));
    tx->clearSenderAndHash();
    BOOST_CHECK_THROW(tx->verify(hashImpl, signatureImpl), std::exception);
}

// N1_T9: empty signature -> verify throws.
BOOST_AUTO_TEST_CASE(N1_T9_empty_signature_throws)
{
    auto tars = buildTars(VECTORS[0], /*prewriteCanonicalHash=*/false);
    tars.signature.clear();
    auto tx = wrap(std::move(tars));
    tx->clearSenderAndHash();
    BOOST_CHECK_THROW(tx->verify(hashImpl, signatureImpl), std::exception);
}

// N1_T10: verify() WITHOUT a preceding clearSenderAndHash() -- the shape of
// TransactionFactoryImpl::createTransaction(checkSig=true), which clears only the sender. The
// recompute is unconditional, so the forged wire hash must be overwritten even on this path
// (no caller discipline required).
BOOST_AUTO_TEST_CASE(N1_T10_verify_without_clear_overwrites_forged_hash)
{
    for (auto const& v : VECTORS)
    {
        auto tars = buildTars(v, /*prewriteCanonicalHash=*/false);
        bcos::bytes forged(32, 0xab);
        tars.extraTransactionHash.assign(forged.begin(), forged.end());
        auto tx = wrap(std::move(tars));
        BOOST_TEST_CONTEXT(v.name)
        {
            BOOST_CHECK(tx->tainted());           // fresh tx: verify() will run
            tx->verify(hashImpl, signatureImpl);  // NO clearSenderAndHash() first
            BOOST_CHECK_EQUAL(tx->hash(), expectedHash(v));
            BOOST_CHECK_NE(tx->hash(), HashType(forged.data(), forged.size()));
        }
    }
}

// N1_T11: legacy preimage with a malformed item count. The EIP-155 branch requires the preimage
// to end with exactly chainId,0,0 -- a 7-item list (chainId but no 0,0 placeholders) and a
// 9-item list with a non-zero trailer must both be rejected, not misread as EIP-155.
BOOST_AUTO_TEST_CASE(N1_T11_legacy_malformed_item_count_throws)
{
    // Derived from legacy_eip155_chain1: rlp header 0xee (payload 46), body ends chainId=01,0,0
    // (bytes "018080").
    auto const& v = VECTORS[1];

    // 7-item list: drop the two 0x80 placeholders, shrink the list header 0xee -> 0xec.
    {
        auto preimage = fromHex(v.preimageHex);
        BOOST_REQUIRE_EQUAL(preimage.front(), 0xee);
        BOOST_REQUIRE_EQUAL(preimage[preimage.size() - 1], 0x80);
        BOOST_REQUIRE_EQUAL(preimage[preimage.size() - 2], 0x80);
        preimage.resize(preimage.size() - 2);
        preimage.front() = 0xec;
        auto tars = buildTars(v, /*prewriteCanonicalHash=*/false);
        tars.extraTransactionBytes.assign(preimage.begin(), preimage.end());
        auto tx = wrap(std::move(tars));
        tx->clearSenderAndHash();
        BOOST_CHECK_THROW(tx->verify(hashImpl, signatureImpl), std::exception);
    }

    // 9-item list with a non-zero trailer: flip the last 0x80 placeholder to 0x01.
    {
        auto preimage = fromHex(v.preimageHex);
        preimage[preimage.size() - 1] = 0x01;
        auto tars = buildTars(v, /*prewriteCanonicalHash=*/false);
        tars.extraTransactionBytes.assign(preimage.begin(), preimage.end());
        auto tx = wrap(std::move(tars));
        tx->clearSenderAndHash();
        BOOST_CHECK_THROW(tx->verify(hashImpl, signatureImpl), std::exception);
    }
}

// F2 txHash contract: calculateHash (the path that writes extraTransactionHash) must
// throw on P||junk *before* storing a hash, so the twin cannot share the victim's txHash.
// Covers typed preimage (admission extraTransactionBytes) and legacy after-list junk.
BOOST_AUTO_TEST_CASE(N1_T12_trailing_junk_cannot_share_txhash)
{
    auto expectHashThrows = [&](Vector const& v, std::string_view stage) {
        auto cleanTars = buildTars(v, /*prewriteCanonicalHash=*/false);
        auto cleanTx = wrap(bcostars::Transaction{cleanTars});
        cleanTx->calculateHash(hashImpl);
        BOOST_CHECK_EQUAL(cleanTx->hash(), expectedHash(v));

        auto junkTars = std::move(cleanTars);
        junkTars.extraTransactionBytes.push_back(static_cast<char>(0xde));
        junkTars.extraTransactionHash.clear();
        auto junkTx = wrap(std::move(junkTars));
        bool threw = false;
        try
        {
            junkTx->calculateHash(hashImpl);
        }
        catch (std::invalid_argument const& e)
        {
            threw = true;
            BOOST_CHECK_MESSAGE(std::string_view(e.what()).find(stage) != std::string_view::npos,
                "expected stage \"" << stage << "\" in what(): " << e.what());
        }
        BOOST_CHECK_MESSAGE(threw, "P||junk must throw so it cannot store the victim's txHash");
        BOOST_CHECK_MESSAGE(junkTx->inner().extraTransactionHash.empty(),
            "calculateHash must not write extraTransactionHash on the junk twin");
    };

    expectHashThrows(VECTORS[3], "typed trailing garbage");  // eip1559 preimage
    expectHashThrows(VECTORS[4], "typed trailing garbage");  // eip2930 preimage
    expectHashThrows(VECTORS[1], "trailing garbage");        // legacy EIP-155 after the outer list
}

BOOST_AUTO_TEST_SUITE_END()

}  // namespace bcos::test
